package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

/**
 * ActionHasActionAttributeId generated by hbm2java
 */
public class ActionHasActionAttributeId implements java.io.Serializable {

  private int actionId;
  private String actionAttributeName;

  public ActionHasActionAttributeId() {
  }

  public ActionHasActionAttributeId(int actionId, String actionAttributeName) {
    this.actionId = actionId;
    this.actionAttributeName = actionAttributeName;
  }

  public int getActionId() {
    return this.actionId;
  }

  public void setActionId(int actionId) {
    this.actionId = actionId;
  }

  public String getActionAttributeName() {
    return this.actionAttributeName;
  }

  public void setActionAttributeName(String actionAttributeName) {
    this.actionAttributeName = actionAttributeName;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof ActionHasActionAttributeId))
      return false;
    ActionHasActionAttributeId castOther = (ActionHasActionAttributeId) other;

    return (this.getActionId() == castOther.getActionId())
        && ((this.getActionAttributeName() == castOther.getActionAttributeName()) || (this.getActionAttributeName() != null
            && castOther.getActionAttributeName() != null && this.getActionAttributeName().equals(
            castOther.getActionAttributeName())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + this.getActionId();
    result = 37 * result + (getActionAttributeName() == null ? 0 : this.getActionAttributeName().hashCode());
    return result;
  }

}
