package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

/**
 * ActionHasActionAttribute generated by hbm2java
 */
public class ActionHasActionAttribute implements java.io.Serializable {

  private ActionHasActionAttributeId id;
  private Action action;
  private ActionAttribute actionAttribute;
  private Double value;

  public ActionHasActionAttribute() {
  }

  public ActionHasActionAttribute(ActionHasActionAttributeId id, Action action, ActionAttribute actionAttribute) {
    this.id = id;
    this.action = action;
    this.actionAttribute = actionAttribute;
  }

  public ActionHasActionAttribute(ActionHasActionAttributeId id, Action action, ActionAttribute actionAttribute, Double value) {
    this.id = id;
    this.action = action;
    this.actionAttribute = actionAttribute;
    this.value = value;
  }

  public ActionHasActionAttributeId getId() {
    return this.id;
  }

  public void setId(ActionHasActionAttributeId id) {
    this.id = id;
  }

  public Action getAction() {
    return this.action;
  }

  public void setAction(Action action) {
    this.action = action;
  }

  public ActionAttribute getActionAttribute() {
    return this.actionAttribute;
  }

  public void setActionAttribute(ActionAttribute actionAttribute) {
    this.actionAttribute = actionAttribute;
  }

  public Double getValue() {
    return this.value;
  }

  public void setValue(Double value) {
    this.value = value;
  }

}
