package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

/**
 * ActionMetric generated by hbm2java
 */
public class ActionMetric implements java.io.Serializable {

  private int actionId;
  private Action action;
  private Double actionReliability;
  private Double actionBalance;
  private Integer numberRequest;

  public ActionMetric() {
  }

  public ActionMetric(Action action) {
    this.action = action;
  }

  public ActionMetric(Action action, Double actionReliability, Double actionBalance, Integer numberRequest) {
    this.action = action;
    this.actionReliability = actionReliability;
    this.actionBalance = actionBalance;
    this.numberRequest = numberRequest;
  }

  public int getActionId() {
    return this.actionId;
  }

  public void setActionId(int actionId) {
    this.actionId = actionId;
  }

  public Action getAction() {
    return this.action;
  }

  public void setAction(Action action) {
    this.action = action;
  }

  public Double getActionReliability() {
    return this.actionReliability;
  }

  public void setActionReliability(Double actionReliability) {
    this.actionReliability = actionReliability;
  }

  public Double getActionBalance() {
    return this.actionBalance;
  }

  public void setActionBalance(Double actionBalance) {
    this.actionBalance = actionBalance;
  }

  public Integer getNumberRequest() {
    return this.numberRequest;
  }

  public void setNumberRequest(Integer numberRequest) {
    this.numberRequest = numberRequest;
  }

}
