package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ActionAttribute generated by hbm2java
 */
public class ActionAttribute implements java.io.Serializable {

  private String name;
  private Set actionHasActionAttributes = new HashSet(0);
  private Set planWeights = new HashSet(0);

  public ActionAttribute() {
  }

  public ActionAttribute(String name) {
    this.name = name;
  }

  public ActionAttribute(String name, Set actionHasActionAttributes, Set planWeights) {
    this.name = name;
    this.actionHasActionAttributes = actionHasActionAttributes;
    this.planWeights = planWeights;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Set getActionHasActionAttributes() {
    return this.actionHasActionAttributes;
  }

  public void setActionHasActionAttributes(Set actionHasActionAttributes) {
    this.actionHasActionAttributes = actionHasActionAttributes;
  }

  public Set getPlanWeights() {
    return this.planWeights;
  }

  public void setPlanWeights(Set planWeights) {
    this.planWeights = planWeights;
  }

}
