package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.validation.constraints.NotNull;

/**
 * Action generated by hbm2java
 */
public class Action implements java.io.Serializable {

  @NotNull
  private int id;
  @NotNull
  private Equipment equipment;
  @NotNull
  private ControlSignal controlSignal;
  @NotNull
  private ActionSla actionSla;
  private Set dailyAvailableReductions = new HashSet(0);
  private ActionMetric actionMetric;
  private Set actionHasActionAttributes = new HashSet(0);
  private ProsumerPreference prosumerPreference;
  @NotNull
  private Set planHasActions = new HashSet(0);

  public Action() {
  }

  public Action(int id, Equipment equipment, ControlSignal controlSignal) {
    this.id = id;
    this.equipment = equipment;
    this.controlSignal = controlSignal;
  }

  public Action(int id, Equipment equipment, ControlSignal controlSignal, ActionSla actionSla, Set dailyAvailableReductions,
      ActionMetric actionMetric, Set actionHasActionAttributes, ProsumerPreference prosumerPreference, Set planHasActions) {
    this.id = id;
    this.equipment = equipment;
    this.controlSignal = controlSignal;
    this.actionSla = actionSla;
    this.dailyAvailableReductions = dailyAvailableReductions;
    this.actionMetric = actionMetric;
    this.actionHasActionAttributes = actionHasActionAttributes;
    this.prosumerPreference = prosumerPreference;
    this.planHasActions = planHasActions;
  }

  public int getId() {
    return this.id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public Equipment getEquipment() {
    return this.equipment;
  }

  public void setEquipment(Equipment equipment) {
    this.equipment = equipment;
  }

  public ControlSignal getControlSignal() {
    return this.controlSignal;
  }

  public void setControlSignal(ControlSignal controlSignal) {
    this.controlSignal = controlSignal;
  }

  public ActionSla getActionSla() {
    return this.actionSla;
  }

  public void setActionSla(ActionSla actionSla) {
    this.actionSla = actionSla;
  }

  public Set getDailyAvailableReductions() {
    return this.dailyAvailableReductions;
  }

  public void setDailyAvailableReductions(Set dailyAvailableReductions) {
    this.dailyAvailableReductions = dailyAvailableReductions;
  }

  public ActionMetric getActionMetric() {
    return this.actionMetric;
  }

  public void setActionMetric(ActionMetric actionMetric) {
    this.actionMetric = actionMetric;
  }

  public Set getActionHasActionAttributes() {
    return this.actionHasActionAttributes;
  }

  public void setActionHasActionAttributes(Set actionHasActionAttributes) {
    this.actionHasActionAttributes = actionHasActionAttributes;
  }

  public ProsumerPreference getProsumerPreference() {
    return this.prosumerPreference;
  }

  public void setProsumerPreference(ProsumerPreference prosumerPreference) {
    this.prosumerPreference = prosumerPreference;
  }

  public Set getPlanHasActions() {
    return this.planHasActions;
  }

  public void setPlanHasActions(Set planHasActions) {
    this.planHasActions = planHasActions;
  }

}
