package com.wattics.vimsen.entities;

// Generated 25-gen-2016 10.15.38 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ControlSignal generated by hbm2java
 */
public class ControlSignal implements java.io.Serializable {

  private int id;
  private String classSignal;
  private String type;
  private String unit;
  private String rangeSignal;
  private String description;
  private String ruleControllerId;
  private Set actions = new HashSet(0);

  public ControlSignal() {
  }

  public ControlSignal(int id) {
    this.id = id;
  }

  public ControlSignal(int id, String classSignal, String type, String unit, String rangeSignal, String description,
      String ruleControllerId, Set actions) {
    this.id = id;
    this.classSignal = classSignal;
    this.type = type;
    this.unit = unit;
    this.rangeSignal = rangeSignal;
    this.description = description;
    this.ruleControllerId = ruleControllerId;
    this.actions = actions;
  }

  public int getId() {
    return this.id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public String getClassSignal() {
    return this.classSignal;
  }

  public void setClassSignal(String classSignal) {
    this.classSignal = classSignal;
  }

  public String getType() {
    return this.type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public String getUnit() {
    return this.unit;
  }

  public void setUnit(String unit) {
    this.unit = unit;
  }

  public String getRangeSignal() {
    return this.rangeSignal;
  }

  public void setRangeSignal(String rangeSignal) {
    this.rangeSignal = rangeSignal;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getRuleControllerId() {
    return this.ruleControllerId;
  }

  public void setRuleControllerId(String ruleControllerId) {
    this.ruleControllerId = ruleControllerId;
  }

  public Set getActions() {
    return this.actions;
  }

  public void setActions(Set actions) {
    this.actions = actions;
  }

}
