package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
public class Country implements java.io.Serializable {

  private int id;
  private String name;
  private Set cities = new HashSet(0);

  public Country() {
  }

  public Country(int id) {
    this.id = id;
  }

  public Country(int id, String name, Set cities) {
    this.id = id;
    this.name = name;
    this.cities = cities;
  }

  public int getId() {
    return this.id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Set getCities() {
    return this.cities;
  }

  public void setCities(Set cities) {
    this.cities = cities;
  }

}
