package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

import org.joda.time.DateTime;

/**
 * DailyAvailableReduction generated by hbm2java
 */
public class DailyAvailableReduction implements java.io.Serializable {

  private DailyAvailableReductionId id;
  private Action action;
  private String reductionCapacity;
  private DateTime endTime;

  public DailyAvailableReduction() {
  }

  public DailyAvailableReduction(DailyAvailableReductionId id, Action action) {
    this.id = id;
    this.action = action;
  }

  public DailyAvailableReduction(DailyAvailableReductionId id, Action action, String reductionCapacity, DateTime endTime) {
    this.id = id;
    this.action = action;
    this.reductionCapacity = reductionCapacity;
    this.endTime = endTime;
  }

  public DailyAvailableReductionId getId() {
    return this.id;
  }

  public void setId(DailyAvailableReductionId id) {
    this.id = id;
  }

  public Action getAction() {
    return this.action;
  }

  public void setAction(Action action) {
    this.action = action;
  }

  public String getReductionCapacity() {
    return this.reductionCapacity;
  }

  public void setReductionCapacity(String reductionCapacity) {
    this.reductionCapacity = reductionCapacity;
  }

  public DateTime getEndTime() {
    return this.endTime;
  }

  public void setEndTime(DateTime endTime) {
    this.endTime = endTime;
  }

}
