package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

/**
 * DssSelectedProsumer generated by hbm2java
 */
public class DssSelectedProsumer implements java.io.Serializable {

  private DssSelectedProsumerId id;
  private MarketSignal marketSignal;
  private Prosumer prosumer;
  private Boolean isPrimary;

  public DssSelectedProsumer() {
  }

  public DssSelectedProsumer(DssSelectedProsumerId id, MarketSignal marketSignal, Prosumer prosumer) {
    this.id = id;
    this.marketSignal = marketSignal;
    this.prosumer = prosumer;
  }

  public DssSelectedProsumer(DssSelectedProsumerId id, MarketSignal marketSignal, Prosumer prosumer, Boolean isPrimary) {
    this.id = id;
    this.marketSignal = marketSignal;
    this.prosumer = prosumer;
    this.isPrimary = isPrimary;
  }

  public DssSelectedProsumerId getId() {
    return this.id;
  }

  public void setId(DssSelectedProsumerId id) {
    this.id = id;
  }

  public MarketSignal getMarketSignal() {
    return this.marketSignal;
  }

  public void setMarketSignal(MarketSignal marketSignal) {
    this.marketSignal = marketSignal;
  }

  public Prosumer getProsumer() {
    return this.prosumer;
  }

  public void setProsumer(Prosumer prosumer) {
    this.prosumer = prosumer;
  }

  public Boolean getIsPrimary() {
    return this.isPrimary;
  }

  public void setIsPrimary(Boolean isPrimary) {
    this.isPrimary = isPrimary;
  }

}
