package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

/**
 * DssSelectedProsumerId generated by hbm2java
 */
public class DssSelectedProsumerId implements java.io.Serializable {

  private int prosumerId;
  private int marketSignalId;

  public DssSelectedProsumerId() {
  }

  public DssSelectedProsumerId(int prosumerId, int marketSignalId) {
    this.prosumerId = prosumerId;
    this.marketSignalId = marketSignalId;
  }

  public int getProsumerId() {
    return this.prosumerId;
  }

  public void setProsumerId(int prosumerId) {
    this.prosumerId = prosumerId;
  }

  public int getMarketSignalId() {
    return this.marketSignalId;
  }

  public void setMarketSignalId(int marketSignalId) {
    this.marketSignalId = marketSignalId;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof DssSelectedProsumerId))
      return false;
    DssSelectedProsumerId castOther = (DssSelectedProsumerId) other;

    return (this.getProsumerId() == castOther.getProsumerId()) && (this.getMarketSignalId() == castOther.getMarketSignalId());
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + this.getProsumerId();
    result = 37 * result + this.getMarketSignalId();
    return result;
  }

}
