package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

import org.joda.time.DateTime;

/**
 * ElectricityRaw generated by hbm2java
 */
public class ElectricityRaw implements java.io.Serializable {

  private int equipmentId;
  private DateTime timestamp;
  private Equipment equipment;
  private Double activePowerA;
  private Double reactivePowerA;
  private Double activePowerB;
  private Double reactivePowerB;
  private Double activePowerC;
  private Double reactivePowerC;

  public ElectricityRaw() {
  }

  public ElectricityRaw(Equipment equipment) {
    this.equipment = equipment;
  }

  public ElectricityRaw(Equipment equipment, Double activePowerA, Double reactivePowerA, Double activePowerB,
      Double reactivePowerB, Double activePowerC, Double reactivePowerC) {
    this.equipment = equipment;
    this.activePowerA = activePowerA;
    this.reactivePowerA = reactivePowerA;
    this.activePowerB = activePowerB;
    this.reactivePowerB = reactivePowerB;
    this.activePowerC = activePowerC;
    this.reactivePowerC = reactivePowerC;
  }

  public int getEquipmentId() {
    return this.equipmentId;
  }

  public void setEquipmentId(int equipmentId) {
    this.equipmentId = equipmentId;
  }

  public DateTime getTimestamp() {
    return this.timestamp;
  }

  public void setTimestamp(DateTime timestamp) {
    this.timestamp = timestamp;
  }

  public Equipment getEquipment() {
    return this.equipment;
  }

  public void setEquipment(Equipment equipment) {
    this.equipment = equipment;
  }

  public Double getActivePowerA() {
    return this.activePowerA;
  }

  public void setActivePowerA(Double activePowerA) {
    this.activePowerA = activePowerA;
  }

  public Double getReactivePowerA() {
    return this.reactivePowerA;
  }

  public void setReactivePowerA(Double reactivePowerA) {
    this.reactivePowerA = reactivePowerA;
  }

  public Double getActivePowerB() {
    return this.activePowerB;
  }

  public void setActivePowerB(Double activePowerB) {
    this.activePowerB = activePowerB;
  }

  public Double getReactivePowerB() {
    return this.reactivePowerB;
  }

  public void setReactivePowerB(Double reactivePowerB) {
    this.reactivePowerB = reactivePowerB;
  }

  public Double getActivePowerC() {
    return this.activePowerC;
  }

  public void setActivePowerC(Double activePowerC) {
    this.activePowerC = activePowerC;
  }

  public Double getReactivePowerC() {
    return this.reactivePowerC;
  }

  public void setReactivePowerC(Double reactivePowerC) {
    this.reactivePowerC = reactivePowerC;
  }

}
