package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

import org.joda.time.DateTime;

/**
 * EquipmentConditionRaw generated by hbm2java
 */
public class EquipmentConditionRaw implements java.io.Serializable {

  private int id;
  private DateTime timestamp;
  private Equipment equipment;
  private String type;
  private Double value;

  public EquipmentConditionRaw() {
  }

  public EquipmentConditionRaw(int id, Equipment equipment) {
    this.id = id;
    this.equipment = equipment;
  }

  public EquipmentConditionRaw(int id, Equipment equipment, String type, Double value) {
    this.id = id;
    this.equipment = equipment;
    this.type = type;
    this.value = value;
  }

  public int getId() {
    return this.id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public DateTime getTimestamp() {
    return this.timestamp;
  }

  public void setTimestamp(DateTime timestamp) {
    this.timestamp = timestamp;
  }

  public Equipment getEquipment() {
    return this.equipment;
  }

  public void setEquipment(Equipment equipment) {
    this.equipment = equipment;
  }

  public String getType() {
    return this.type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Double getValue() {
    return this.value;
  }

  public void setValue(Double value) {
    this.value = value;
  }

}
