package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Equipment generated by hbm2java
 */
public class Equipment implements java.io.Serializable {

  private int id;
  @NotNull
  private Site site;
  @NotNull
  private String name;
  private String class_;
  @NotNull
  private String category;
  private String brand;
  private String model;
  private Set kwhForecasts = new HashSet(0);
  private EquipmentConditionProfile equipmentConditionProfile;
  private ReschedulableFootprint reschedulableFootprint;
  private Set equipmentConditionRaws = new HashSet(0);
  private ReducibleFootprint reducibleFootprint;
  private GeneratorFootprint generatorFootprint;
  private Set kwhBoundarieses = new HashSet(0);
  private StorableFootprint storableFootprint;
  private Set kwh5mns = new HashSet(0);
  private Set operatingStates = new HashSet(0);
  @Size(min = 1)
  private Set actions = new HashSet(0);
  private Set kwhHourlies = new HashSet(0);
  private ElectricityRaw electricityRaw;
  private Set kwh15mns = new HashSet(0);

  public Equipment() {
  }

  public Equipment(int id, Site site) {
    this.id = id;
    this.site = site;
  }

  public Equipment(int id, Site site, String name, String class_, String category, String brand, String model, Set kwhForecasts,
      EquipmentConditionProfile equipmentConditionProfile, ReschedulableFootprint reschedulableFootprint,
      Set equipmentConditionRaws, ReducibleFootprint reducibleFootprint, GeneratorFootprint generatorFootprint,
      Set kwhBoundarieses, StorableFootprint storableFootprint, Set kwh5mns, Set operatingStates, Set actions, Set kwhHourlies,
      ElectricityRaw electricityRaw, Set kwh15mns) {
    this.id = id;
    this.site = site;
    this.name = name;
    this.class_ = class_;
    this.category = category;
    this.brand = brand;
    this.model = model;
    this.kwhForecasts = kwhForecasts;
    this.equipmentConditionProfile = equipmentConditionProfile;
    this.reschedulableFootprint = reschedulableFootprint;
    this.equipmentConditionRaws = equipmentConditionRaws;
    this.reducibleFootprint = reducibleFootprint;
    this.generatorFootprint = generatorFootprint;
    this.kwhBoundarieses = kwhBoundarieses;
    this.storableFootprint = storableFootprint;
    this.kwh5mns = kwh5mns;
    this.operatingStates = operatingStates;
    this.actions = actions;
    this.kwhHourlies = kwhHourlies;
    this.electricityRaw = electricityRaw;
    this.kwh15mns = kwh15mns;
  }

  public int getId() {
    return this.id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public Site getSite() {
    return this.site;
  }

  public void setSite(Site site) {
    this.site = site;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getClass_() {
    return this.class_;
  }

  public void setClass_(String class_) {
    this.class_ = class_;
  }

  public String getCategory() {
    return this.category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public String getBrand() {
    return this.brand;
  }

  public void setBrand(String brand) {
    this.brand = brand;
  }

  public String getModel() {
    return this.model;
  }

  public void setModel(String model) {
    this.model = model;
  }

  public Set getKwhForecasts() {
    return this.kwhForecasts;
  }

  public void setKwhForecasts(Set kwhForecasts) {
    this.kwhForecasts = kwhForecasts;
  }

  public EquipmentConditionProfile getEquipmentConditionProfile() {
    return this.equipmentConditionProfile;
  }

  public void setEquipmentConditionProfile(EquipmentConditionProfile equipmentConditionProfile) {
    this.equipmentConditionProfile = equipmentConditionProfile;
  }

  public ReschedulableFootprint getReschedulableFootprint() {
    return this.reschedulableFootprint;
  }

  public void setReschedulableFootprint(ReschedulableFootprint reschedulableFootprint) {
    this.reschedulableFootprint = reschedulableFootprint;
  }

  public Set getEquipmentConditionRaws() {
    return this.equipmentConditionRaws;
  }

  public void setEquipmentConditionRaws(Set equipmentConditionRaws) {
    this.equipmentConditionRaws = equipmentConditionRaws;
  }

  public ReducibleFootprint getReducibleFootprint() {
    return this.reducibleFootprint;
  }

  public void setReducibleFootprint(ReducibleFootprint reducibleFootprint) {
    this.reducibleFootprint = reducibleFootprint;
  }

  public GeneratorFootprint getGeneratorFootprint() {
    return this.generatorFootprint;
  }

  public void setGeneratorFootprint(GeneratorFootprint generatorFootprint) {
    this.generatorFootprint = generatorFootprint;
  }

  public Set getKwhBoundarieses() {
    return this.kwhBoundarieses;
  }

  public void setKwhBoundarieses(Set kwhBoundarieses) {
    this.kwhBoundarieses = kwhBoundarieses;
  }

  public StorableFootprint getStorableFootprint() {
    return this.storableFootprint;
  }

  public void setStorableFootprint(StorableFootprint storableFootprint) {
    this.storableFootprint = storableFootprint;
  }

  public Set getKwh5mns() {
    return this.kwh5mns;
  }

  public void setKwh5mns(Set kwh5mns) {
    this.kwh5mns = kwh5mns;
  }

  public Set getOperatingStates() {
    return this.operatingStates;
  }

  public void setOperatingStates(Set operatingStates) {
    this.operatingStates = operatingStates;
  }

  public Set getActions() {
    return this.actions;
  }

  public void setActions(Set actions) {
    this.actions = actions;
  }

  public Set getKwhHourlies() {
    return this.kwhHourlies;
  }

  public void setKwhHourlies(Set kwhHourlies) {
    this.kwhHourlies = kwhHourlies;
  }

  public ElectricityRaw getElectricityRaw() {
    return this.electricityRaw;
  }

  public void setElectricityRaw(ElectricityRaw electricityRaw) {
    this.electricityRaw = electricityRaw;
  }

  public Set getKwh15mns() {
    return this.kwh15mns;
  }

  public void setKwh15mns(Set kwh15mns) {
    this.kwh15mns = kwh15mns;
  }

}
