package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

import org.joda.time.DateTime;

/**
 * Kwh5mnId generated by hbm2java
 */
public class Kwh5mnId implements java.io.Serializable {

  private int equipmentId;
  private DateTime date;

  public Kwh5mnId() {
  }

  public Kwh5mnId(int equipmentId, DateTime date) {
    this.equipmentId = equipmentId;
    this.date = date;
  }

  public int getEquipmentId() {
    return this.equipmentId;
  }

  public void setEquipmentId(int equipmentId) {
    this.equipmentId = equipmentId;
  }

  public DateTime getDate() {
    return this.date;
  }

  public void setDate(DateTime date) {
    this.date = date;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof Kwh5mnId))
      return false;
    Kwh5mnId castOther = (Kwh5mnId) other;

    return (this.getEquipmentId() == castOther.getEquipmentId())
        && ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null && this.getDate()
            .equals(castOther.getDate())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + this.getEquipmentId();
    result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
    return result;
  }

}
