package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

/**
 * Kwh5mn generated by hbm2java
 */
public class Kwh5mn implements java.io.Serializable {

  private Kwh5mnId id;
  private Equipment equipment;
  private Double t0000;
  private Double t0005;
  private Double t0010;
  private Double t0015;
  private Double t0020;
  private Double t0025;
  private Double t0030;
  private Double t0035;
  private Double t0040;
  private Double t0045;
  private Double t0050;
  private Double t0055;
  private Double t0100;
  private Double t0105;
  private Double t0110;
  private Double t0115;
  private Double t0120;
  private Double t0125;
  private Double t0130;
  private Double t0135;
  private Double t0140;
  private Double t0145;
  private Double t0150;
  private Double t0155;
  private Double t0200;
  private Double t0205;
  private Double t0210;
  private Double t0215;
  private Double t0220;
  private Double t0225;
  private Double t0230;
  private Double t0235;
  private Double t0240;
  private Double t0245;
  private Double t0250;
  private Double t0255;
  private Double t0300;
  private Double t0305;
  private Double t0310;
  private Double t0315;
  private Double t0320;
  private Double t0325;
  private Double t0330;
  private Double t0335;
  private Double t0340;
  private Double t0345;
  private Double t0350;
  private Double t0355;
  private Double t0400;
  private Double t0405;
  private Double t0410;
  private Double t0415;
  private Double t0420;
  private Double t0425;
  private Double t0430;
  private Double t0435;
  private Double t0440;
  private Double t0445;
  private Double t0450;
  private Double t0455;
  private Double t0500;
  private Double t0505;
  private Double t0510;
  private Double t0515;
  private Double t0520;
  private Double t0525;
  private Double t0530;
  private Double t0535;
  private Double t0540;
  private Double t0545;
  private Double t0550;
  private Double t0555;
  private Double t0600;
  private Double t0605;
  private Double t0610;
  private Double t0615;
  private Double t0620;
  private Double t0625;
  private Double t0630;
  private Double t0635;
  private Double t0640;
  private Double t0645;
  private Double t0650;
  private Double t0655;
  private Double t0700;
  private Double t0705;
  private Double t0710;
  private Double t0715;
  private Double t0720;
  private Double t0725;
  private Double t0730;
  private Double t0735;
  private Double t0740;
  private Double t0745;
  private Double t0750;
  private Double t0755;
  private Double t0800;
  private Double t0805;
  private Double t0810;
  private Double t0815;
  private Double t0820;
  private Double t0825;
  private Double t0830;
  private Double t0835;
  private Double t0840;
  private Double t0845;
  private Double t0850;
  private Double t0855;
  private Double t0900;
  private Double t0905;
  private Double t0910;
  private Double t0915;
  private Double t0920;
  private Double t0925;
  private Double t0930;
  private Double t0935;
  private Double t0940;
  private Double t0945;
  private Double t0950;
  private Double t0955;
  private Double t1000;
  private Double t1005;
  private Double t1010;
  private Double t1015;
  private Double t1020;
  private Double t1025;
  private Double t1030;
  private Double t1035;
  private Double t1040;
  private Double t1045;
  private Double t1050;
  private Double t1055;
  private Double t1100;
  private Double t1105;
  private Double t1110;
  private Double t1115;
  private Double t1120;
  private Double t1125;
  private Double t1130;
  private Double t1135;
  private Double t1140;
  private Double t1145;
  private Double t1150;
  private Double t1155;
  private Double t1200;
  private Double t1205;
  private Double t1210;
  private Double t1215;
  private Double t1220;
  private Double t1225;
  private Double t1230;
  private Double t1235;
  private Double t1240;
  private Double t1245;
  private Double t1250;
  private Double t1255;
  private Double t1300;
  private Double t1305;
  private Double t1310;
  private Double t1315;
  private Double t1320;
  private Double t1325;
  private Double t1330;
  private Double t1335;
  private Double t1340;
  private Double t1345;
  private Double t1350;
  private Double t1355;
  private Double t1400;
  private Double t1405;
  private Double t1410;
  private Double t1415;
  private Double t1420;
  private Double t1425;
  private Double t1430;
  private Double t1435;
  private Double t1440;
  private Double t1445;
  private Double t1450;
  private Double t1455;
  private Double t1500;
  private Double t1505;
  private Double t1510;
  private Double t1515;
  private Double t1520;
  private Double t1525;
  private Double t1530;
  private Double t1535;
  private Double t1540;
  private Double t1545;
  private Double t1550;
  private Double t1555;
  private Double t1600;
  private Double t1605;
  private Double t1610;
  private Double t1615;
  private Double t1620;
  private Double t1625;
  private Double t1630;
  private Double t1635;
  private Double t1640;
  private Double t1645;
  private Double t1650;
  private Double t1655;
  private Double t1700;
  private Double t1705;
  private Double t1710;
  private Double t1715;
  private Double t1720;
  private Double t1725;
  private Double t1730;
  private Double t1735;
  private Double t1740;
  private Double t1745;
  private Double t1750;
  private Double t1755;
  private Double t1800;
  private Double t1805;
  private Double t1810;
  private Double t1815;
  private Double t1820;
  private Double t1825;
  private Double t1830;
  private Double t1835;
  private Double t1840;
  private Double t1845;
  private Double t1850;
  private Double t1855;
  private Double t1900;
  private Double t1905;
  private Double t1910;
  private Double t1915;
  private Double t1920;
  private Double t1925;
  private Double t1930;
  private Double t1935;
  private Double t1940;
  private Double t1945;
  private Double t1950;
  private Double t1955;
  private Double t2000;
  private Double t2005;
  private Double t2010;
  private Double t2015;
  private Double t2020;
  private Double t2025;
  private Double t2030;
  private Double t2035;
  private Double t2040;
  private Double t2045;
  private Double t2050;
  private Double t2055;
  private Double t2100;
  private Double t2105;
  private Double t2110;
  private Double t2115;
  private Double t2120;
  private Double t2125;
  private Double t2130;
  private Double t2135;
  private Double t2140;
  private Double t2145;
  private Double t2150;
  private Double t2155;
  private Double t2200;
  private Double t2205;
  private Double t2210;
  private Double t2215;
  private Double t2220;
  private Double t2225;
  private Double t2230;
  private Double t2235;
  private Double t2240;
  private Double t2245;
  private Double t2250;
  private Double t2255;
  private Double t2300;
  private Double t2305;
  private Double t2310;
  private Double t2315;
  private Double t2320;
  private Double t2325;
  private Double t2330;
  private Double t2335;
  private Double t2340;
  private Double t2345;
  private Double t2350;
  private Double t2355;

  public Kwh5mn() {
  }

  public Kwh5mn(Kwh5mnId id, Equipment equipment) {
    this.id = id;
    this.equipment = equipment;
  }

  public Kwh5mnId getId() {
    return this.id;
  }

  public void setId(Kwh5mnId id) {
    this.id = id;
  }

  public Equipment getEquipment() {
    return this.equipment;
  }

  public void setEquipment(Equipment equipment) {
    this.equipment = equipment;
  }

  public Double getT0000() {
    return this.t0000;
  }

  public void setT0000(Double t0000) {
    this.t0000 = t0000;
  }

  public Double getT0005() {
    return this.t0005;
  }

  public void setT0005(Double t0005) {
    this.t0005 = t0005;
  }

  public Double getT0010() {
    return this.t0010;
  }

  public void setT0010(Double t0010) {
    this.t0010 = t0010;
  }

  public Double getT0015() {
    return this.t0015;
  }

  public void setT0015(Double t0015) {
    this.t0015 = t0015;
  }

  public Double getT0020() {
    return this.t0020;
  }

  public void setT0020(Double t0020) {
    this.t0020 = t0020;
  }

  public Double getT0025() {
    return this.t0025;
  }

  public void setT0025(Double t0025) {
    this.t0025 = t0025;
  }

  public Double getT0030() {
    return this.t0030;
  }

  public void setT0030(Double t0030) {
    this.t0030 = t0030;
  }

  public Double getT0035() {
    return this.t0035;
  }

  public void setT0035(Double t0035) {
    this.t0035 = t0035;
  }

  public Double getT0040() {
    return this.t0040;
  }

  public void setT0040(Double t0040) {
    this.t0040 = t0040;
  }

  public Double getT0045() {
    return this.t0045;
  }

  public void setT0045(Double t0045) {
    this.t0045 = t0045;
  }

  public Double getT0050() {
    return this.t0050;
  }

  public void setT0050(Double t0050) {
    this.t0050 = t0050;
  }

  public Double getT0055() {
    return this.t0055;
  }

  public void setT0055(Double t0055) {
    this.t0055 = t0055;
  }

  public Double getT0100() {
    return this.t0100;
  }

  public void setT0100(Double t0100) {
    this.t0100 = t0100;
  }

  public Double getT0105() {
    return this.t0105;
  }

  public void setT0105(Double t0105) {
    this.t0105 = t0105;
  }

  public Double getT0110() {
    return this.t0110;
  }

  public void setT0110(Double t0110) {
    this.t0110 = t0110;
  }

  public Double getT0115() {
    return this.t0115;
  }

  public void setT0115(Double t0115) {
    this.t0115 = t0115;
  }

  public Double getT0120() {
    return this.t0120;
  }

  public void setT0120(Double t0120) {
    this.t0120 = t0120;
  }

  public Double getT0125() {
    return this.t0125;
  }

  public void setT0125(Double t0125) {
    this.t0125 = t0125;
  }

  public Double getT0130() {
    return this.t0130;
  }

  public void setT0130(Double t0130) {
    this.t0130 = t0130;
  }

  public Double getT0135() {
    return this.t0135;
  }

  public void setT0135(Double t0135) {
    this.t0135 = t0135;
  }

  public Double getT0140() {
    return this.t0140;
  }

  public void setT0140(Double t0140) {
    this.t0140 = t0140;
  }

  public Double getT0145() {
    return this.t0145;
  }

  public void setT0145(Double t0145) {
    this.t0145 = t0145;
  }

  public Double getT0150() {
    return this.t0150;
  }

  public void setT0150(Double t0150) {
    this.t0150 = t0150;
  }

  public Double getT0155() {
    return this.t0155;
  }

  public void setT0155(Double t0155) {
    this.t0155 = t0155;
  }

  public Double getT0200() {
    return this.t0200;
  }

  public void setT0200(Double t0200) {
    this.t0200 = t0200;
  }

  public Double getT0205() {
    return this.t0205;
  }

  public void setT0205(Double t0205) {
    this.t0205 = t0205;
  }

  public Double getT0210() {
    return this.t0210;
  }

  public void setT0210(Double t0210) {
    this.t0210 = t0210;
  }

  public Double getT0215() {
    return this.t0215;
  }

  public void setT0215(Double t0215) {
    this.t0215 = t0215;
  }

  public Double getT0220() {
    return this.t0220;
  }

  public void setT0220(Double t0220) {
    this.t0220 = t0220;
  }

  public Double getT0225() {
    return this.t0225;
  }

  public void setT0225(Double t0225) {
    this.t0225 = t0225;
  }

  public Double getT0230() {
    return this.t0230;
  }

  public void setT0230(Double t0230) {
    this.t0230 = t0230;
  }

  public Double getT0235() {
    return this.t0235;
  }

  public void setT0235(Double t0235) {
    this.t0235 = t0235;
  }

  public Double getT0240() {
    return this.t0240;
  }

  public void setT0240(Double t0240) {
    this.t0240 = t0240;
  }

  public Double getT0245() {
    return this.t0245;
  }

  public void setT0245(Double t0245) {
    this.t0245 = t0245;
  }

  public Double getT0250() {
    return this.t0250;
  }

  public void setT0250(Double t0250) {
    this.t0250 = t0250;
  }

  public Double getT0255() {
    return this.t0255;
  }

  public void setT0255(Double t0255) {
    this.t0255 = t0255;
  }

  public Double getT0300() {
    return this.t0300;
  }

  public void setT0300(Double t0300) {
    this.t0300 = t0300;
  }

  public Double getT0305() {
    return this.t0305;
  }

  public void setT0305(Double t0305) {
    this.t0305 = t0305;
  }

  public Double getT0310() {
    return this.t0310;
  }

  public void setT0310(Double t0310) {
    this.t0310 = t0310;
  }

  public Double getT0315() {
    return this.t0315;
  }

  public void setT0315(Double t0315) {
    this.t0315 = t0315;
  }

  public Double getT0320() {
    return this.t0320;
  }

  public void setT0320(Double t0320) {
    this.t0320 = t0320;
  }

  public Double getT0325() {
    return this.t0325;
  }

  public void setT0325(Double t0325) {
    this.t0325 = t0325;
  }

  public Double getT0330() {
    return this.t0330;
  }

  public void setT0330(Double t0330) {
    this.t0330 = t0330;
  }

  public Double getT0335() {
    return this.t0335;
  }

  public void setT0335(Double t0335) {
    this.t0335 = t0335;
  }

  public Double getT0340() {
    return this.t0340;
  }

  public void setT0340(Double t0340) {
    this.t0340 = t0340;
  }

  public Double getT0345() {
    return this.t0345;
  }

  public void setT0345(Double t0345) {
    this.t0345 = t0345;
  }

  public Double getT0350() {
    return this.t0350;
  }

  public void setT0350(Double t0350) {
    this.t0350 = t0350;
  }

  public Double getT0355() {
    return this.t0355;
  }

  public void setT0355(Double t0355) {
    this.t0355 = t0355;
  }

  public Double getT0400() {
    return this.t0400;
  }

  public void setT0400(Double t0400) {
    this.t0400 = t0400;
  }

  public Double getT0405() {
    return this.t0405;
  }

  public void setT0405(Double t0405) {
    this.t0405 = t0405;
  }

  public Double getT0410() {
    return this.t0410;
  }

  public void setT0410(Double t0410) {
    this.t0410 = t0410;
  }

  public Double getT0415() {
    return this.t0415;
  }

  public void setT0415(Double t0415) {
    this.t0415 = t0415;
  }

  public Double getT0420() {
    return this.t0420;
  }

  public void setT0420(Double t0420) {
    this.t0420 = t0420;
  }

  public Double getT0425() {
    return this.t0425;
  }

  public void setT0425(Double t0425) {
    this.t0425 = t0425;
  }

  public Double getT0430() {
    return this.t0430;
  }

  public void setT0430(Double t0430) {
    this.t0430 = t0430;
  }

  public Double getT0435() {
    return this.t0435;
  }

  public void setT0435(Double t0435) {
    this.t0435 = t0435;
  }

  public Double getT0440() {
    return this.t0440;
  }

  public void setT0440(Double t0440) {
    this.t0440 = t0440;
  }

  public Double getT0445() {
    return this.t0445;
  }

  public void setT0445(Double t0445) {
    this.t0445 = t0445;
  }

  public Double getT0450() {
    return this.t0450;
  }

  public void setT0450(Double t0450) {
    this.t0450 = t0450;
  }

  public Double getT0455() {
    return this.t0455;
  }

  public void setT0455(Double t0455) {
    this.t0455 = t0455;
  }

  public Double getT0500() {
    return this.t0500;
  }

  public void setT0500(Double t0500) {
    this.t0500 = t0500;
  }

  public Double getT0505() {
    return this.t0505;
  }

  public void setT0505(Double t0505) {
    this.t0505 = t0505;
  }

  public Double getT0510() {
    return this.t0510;
  }

  public void setT0510(Double t0510) {
    this.t0510 = t0510;
  }

  public Double getT0515() {
    return this.t0515;
  }

  public void setT0515(Double t0515) {
    this.t0515 = t0515;
  }

  public Double getT0520() {
    return this.t0520;
  }

  public void setT0520(Double t0520) {
    this.t0520 = t0520;
  }

  public Double getT0525() {
    return this.t0525;
  }

  public void setT0525(Double t0525) {
    this.t0525 = t0525;
  }

  public Double getT0530() {
    return this.t0530;
  }

  public void setT0530(Double t0530) {
    this.t0530 = t0530;
  }

  public Double getT0535() {
    return this.t0535;
  }

  public void setT0535(Double t0535) {
    this.t0535 = t0535;
  }

  public Double getT0540() {
    return this.t0540;
  }

  public void setT0540(Double t0540) {
    this.t0540 = t0540;
  }

  public Double getT0545() {
    return this.t0545;
  }

  public void setT0545(Double t0545) {
    this.t0545 = t0545;
  }

  public Double getT0550() {
    return this.t0550;
  }

  public void setT0550(Double t0550) {
    this.t0550 = t0550;
  }

  public Double getT0555() {
    return this.t0555;
  }

  public void setT0555(Double t0555) {
    this.t0555 = t0555;
  }

  public Double getT0600() {
    return this.t0600;
  }

  public void setT0600(Double t0600) {
    this.t0600 = t0600;
  }

  public Double getT0605() {
    return this.t0605;
  }

  public void setT0605(Double t0605) {
    this.t0605 = t0605;
  }

  public Double getT0610() {
    return this.t0610;
  }

  public void setT0610(Double t0610) {
    this.t0610 = t0610;
  }

  public Double getT0615() {
    return this.t0615;
  }

  public void setT0615(Double t0615) {
    this.t0615 = t0615;
  }

  public Double getT0620() {
    return this.t0620;
  }

  public void setT0620(Double t0620) {
    this.t0620 = t0620;
  }

  public Double getT0625() {
    return this.t0625;
  }

  public void setT0625(Double t0625) {
    this.t0625 = t0625;
  }

  public Double getT0630() {
    return this.t0630;
  }

  public void setT0630(Double t0630) {
    this.t0630 = t0630;
  }

  public Double getT0635() {
    return this.t0635;
  }

  public void setT0635(Double t0635) {
    this.t0635 = t0635;
  }

  public Double getT0640() {
    return this.t0640;
  }

  public void setT0640(Double t0640) {
    this.t0640 = t0640;
  }

  public Double getT0645() {
    return this.t0645;
  }

  public void setT0645(Double t0645) {
    this.t0645 = t0645;
  }

  public Double getT0650() {
    return this.t0650;
  }

  public void setT0650(Double t0650) {
    this.t0650 = t0650;
  }

  public Double getT0655() {
    return this.t0655;
  }

  public void setT0655(Double t0655) {
    this.t0655 = t0655;
  }

  public Double getT0700() {
    return this.t0700;
  }

  public void setT0700(Double t0700) {
    this.t0700 = t0700;
  }

  public Double getT0705() {
    return this.t0705;
  }

  public void setT0705(Double t0705) {
    this.t0705 = t0705;
  }

  public Double getT0710() {
    return this.t0710;
  }

  public void setT0710(Double t0710) {
    this.t0710 = t0710;
  }

  public Double getT0715() {
    return this.t0715;
  }

  public void setT0715(Double t0715) {
    this.t0715 = t0715;
  }

  public Double getT0720() {
    return this.t0720;
  }

  public void setT0720(Double t0720) {
    this.t0720 = t0720;
  }

  public Double getT0725() {
    return this.t0725;
  }

  public void setT0725(Double t0725) {
    this.t0725 = t0725;
  }

  public Double getT0730() {
    return this.t0730;
  }

  public void setT0730(Double t0730) {
    this.t0730 = t0730;
  }

  public Double getT0735() {
    return this.t0735;
  }

  public void setT0735(Double t0735) {
    this.t0735 = t0735;
  }

  public Double getT0740() {
    return this.t0740;
  }

  public void setT0740(Double t0740) {
    this.t0740 = t0740;
  }

  public Double getT0745() {
    return this.t0745;
  }

  public void setT0745(Double t0745) {
    this.t0745 = t0745;
  }

  public Double getT0750() {
    return this.t0750;
  }

  public void setT0750(Double t0750) {
    this.t0750 = t0750;
  }

  public Double getT0755() {
    return this.t0755;
  }

  public void setT0755(Double t0755) {
    this.t0755 = t0755;
  }

  public Double getT0800() {
    return this.t0800;
  }

  public void setT0800(Double t0800) {
    this.t0800 = t0800;
  }

  public Double getT0805() {
    return this.t0805;
  }

  public void setT0805(Double t0805) {
    this.t0805 = t0805;
  }

  public Double getT0810() {
    return this.t0810;
  }

  public void setT0810(Double t0810) {
    this.t0810 = t0810;
  }

  public Double getT0815() {
    return this.t0815;
  }

  public void setT0815(Double t0815) {
    this.t0815 = t0815;
  }

  public Double getT0820() {
    return this.t0820;
  }

  public void setT0820(Double t0820) {
    this.t0820 = t0820;
  }

  public Double getT0825() {
    return this.t0825;
  }

  public void setT0825(Double t0825) {
    this.t0825 = t0825;
  }

  public Double getT0830() {
    return this.t0830;
  }

  public void setT0830(Double t0830) {
    this.t0830 = t0830;
  }

  public Double getT0835() {
    return this.t0835;
  }

  public void setT0835(Double t0835) {
    this.t0835 = t0835;
  }

  public Double getT0840() {
    return this.t0840;
  }

  public void setT0840(Double t0840) {
    this.t0840 = t0840;
  }

  public Double getT0845() {
    return this.t0845;
  }

  public void setT0845(Double t0845) {
    this.t0845 = t0845;
  }

  public Double getT0850() {
    return this.t0850;
  }

  public void setT0850(Double t0850) {
    this.t0850 = t0850;
  }

  public Double getT0855() {
    return this.t0855;
  }

  public void setT0855(Double t0855) {
    this.t0855 = t0855;
  }

  public Double getT0900() {
    return this.t0900;
  }

  public void setT0900(Double t0900) {
    this.t0900 = t0900;
  }

  public Double getT0905() {
    return this.t0905;
  }

  public void setT0905(Double t0905) {
    this.t0905 = t0905;
  }

  public Double getT0910() {
    return this.t0910;
  }

  public void setT0910(Double t0910) {
    this.t0910 = t0910;
  }

  public Double getT0915() {
    return this.t0915;
  }

  public void setT0915(Double t0915) {
    this.t0915 = t0915;
  }

  public Double getT0920() {
    return this.t0920;
  }

  public void setT0920(Double t0920) {
    this.t0920 = t0920;
  }

  public Double getT0925() {
    return this.t0925;
  }

  public void setT0925(Double t0925) {
    this.t0925 = t0925;
  }

  public Double getT0930() {
    return this.t0930;
  }

  public void setT0930(Double t0930) {
    this.t0930 = t0930;
  }

  public Double getT0935() {
    return this.t0935;
  }

  public void setT0935(Double t0935) {
    this.t0935 = t0935;
  }

  public Double getT0940() {
    return this.t0940;
  }

  public void setT0940(Double t0940) {
    this.t0940 = t0940;
  }

  public Double getT0945() {
    return this.t0945;
  }

  public void setT0945(Double t0945) {
    this.t0945 = t0945;
  }

  public Double getT0950() {
    return this.t0950;
  }

  public void setT0950(Double t0950) {
    this.t0950 = t0950;
  }

  public Double getT0955() {
    return this.t0955;
  }

  public void setT0955(Double t0955) {
    this.t0955 = t0955;
  }

  public Double getT1000() {
    return this.t1000;
  }

  public void setT1000(Double t1000) {
    this.t1000 = t1000;
  }

  public Double getT1005() {
    return this.t1005;
  }

  public void setT1005(Double t1005) {
    this.t1005 = t1005;
  }

  public Double getT1010() {
    return this.t1010;
  }

  public void setT1010(Double t1010) {
    this.t1010 = t1010;
  }

  public Double getT1015() {
    return this.t1015;
  }

  public void setT1015(Double t1015) {
    this.t1015 = t1015;
  }

  public Double getT1020() {
    return this.t1020;
  }

  public void setT1020(Double t1020) {
    this.t1020 = t1020;
  }

  public Double getT1025() {
    return this.t1025;
  }

  public void setT1025(Double t1025) {
    this.t1025 = t1025;
  }

  public Double getT1030() {
    return this.t1030;
  }

  public void setT1030(Double t1030) {
    this.t1030 = t1030;
  }

  public Double getT1035() {
    return this.t1035;
  }

  public void setT1035(Double t1035) {
    this.t1035 = t1035;
  }

  public Double getT1040() {
    return this.t1040;
  }

  public void setT1040(Double t1040) {
    this.t1040 = t1040;
  }

  public Double getT1045() {
    return this.t1045;
  }

  public void setT1045(Double t1045) {
    this.t1045 = t1045;
  }

  public Double getT1050() {
    return this.t1050;
  }

  public void setT1050(Double t1050) {
    this.t1050 = t1050;
  }

  public Double getT1055() {
    return this.t1055;
  }

  public void setT1055(Double t1055) {
    this.t1055 = t1055;
  }

  public Double getT1100() {
    return this.t1100;
  }

  public void setT1100(Double t1100) {
    this.t1100 = t1100;
  }

  public Double getT1105() {
    return this.t1105;
  }

  public void setT1105(Double t1105) {
    this.t1105 = t1105;
  }

  public Double getT1110() {
    return this.t1110;
  }

  public void setT1110(Double t1110) {
    this.t1110 = t1110;
  }

  public Double getT1115() {
    return this.t1115;
  }

  public void setT1115(Double t1115) {
    this.t1115 = t1115;
  }

  public Double getT1120() {
    return this.t1120;
  }

  public void setT1120(Double t1120) {
    this.t1120 = t1120;
  }

  public Double getT1125() {
    return this.t1125;
  }

  public void setT1125(Double t1125) {
    this.t1125 = t1125;
  }

  public Double getT1130() {
    return this.t1130;
  }

  public void setT1130(Double t1130) {
    this.t1130 = t1130;
  }

  public Double getT1135() {
    return this.t1135;
  }

  public void setT1135(Double t1135) {
    this.t1135 = t1135;
  }

  public Double getT1140() {
    return this.t1140;
  }

  public void setT1140(Double t1140) {
    this.t1140 = t1140;
  }

  public Double getT1145() {
    return this.t1145;
  }

  public void setT1145(Double t1145) {
    this.t1145 = t1145;
  }

  public Double getT1150() {
    return this.t1150;
  }

  public void setT1150(Double t1150) {
    this.t1150 = t1150;
  }

  public Double getT1155() {
    return this.t1155;
  }

  public void setT1155(Double t1155) {
    this.t1155 = t1155;
  }

  public Double getT1200() {
    return this.t1200;
  }

  public void setT1200(Double t1200) {
    this.t1200 = t1200;
  }

  public Double getT1205() {
    return this.t1205;
  }

  public void setT1205(Double t1205) {
    this.t1205 = t1205;
  }

  public Double getT1210() {
    return this.t1210;
  }

  public void setT1210(Double t1210) {
    this.t1210 = t1210;
  }

  public Double getT1215() {
    return this.t1215;
  }

  public void setT1215(Double t1215) {
    this.t1215 = t1215;
  }

  public Double getT1220() {
    return this.t1220;
  }

  public void setT1220(Double t1220) {
    this.t1220 = t1220;
  }

  public Double getT1225() {
    return this.t1225;
  }

  public void setT1225(Double t1225) {
    this.t1225 = t1225;
  }

  public Double getT1230() {
    return this.t1230;
  }

  public void setT1230(Double t1230) {
    this.t1230 = t1230;
  }

  public Double getT1235() {
    return this.t1235;
  }

  public void setT1235(Double t1235) {
    this.t1235 = t1235;
  }

  public Double getT1240() {
    return this.t1240;
  }

  public void setT1240(Double t1240) {
    this.t1240 = t1240;
  }

  public Double getT1245() {
    return this.t1245;
  }

  public void setT1245(Double t1245) {
    this.t1245 = t1245;
  }

  public Double getT1250() {
    return this.t1250;
  }

  public void setT1250(Double t1250) {
    this.t1250 = t1250;
  }

  public Double getT1255() {
    return this.t1255;
  }

  public void setT1255(Double t1255) {
    this.t1255 = t1255;
  }

  public Double getT1300() {
    return this.t1300;
  }

  public void setT1300(Double t1300) {
    this.t1300 = t1300;
  }

  public Double getT1305() {
    return this.t1305;
  }

  public void setT1305(Double t1305) {
    this.t1305 = t1305;
  }

  public Double getT1310() {
    return this.t1310;
  }

  public void setT1310(Double t1310) {
    this.t1310 = t1310;
  }

  public Double getT1315() {
    return this.t1315;
  }

  public void setT1315(Double t1315) {
    this.t1315 = t1315;
  }

  public Double getT1320() {
    return this.t1320;
  }

  public void setT1320(Double t1320) {
    this.t1320 = t1320;
  }

  public Double getT1325() {
    return this.t1325;
  }

  public void setT1325(Double t1325) {
    this.t1325 = t1325;
  }

  public Double getT1330() {
    return this.t1330;
  }

  public void setT1330(Double t1330) {
    this.t1330 = t1330;
  }

  public Double getT1335() {
    return this.t1335;
  }

  public void setT1335(Double t1335) {
    this.t1335 = t1335;
  }

  public Double getT1340() {
    return this.t1340;
  }

  public void setT1340(Double t1340) {
    this.t1340 = t1340;
  }

  public Double getT1345() {
    return this.t1345;
  }

  public void setT1345(Double t1345) {
    this.t1345 = t1345;
  }

  public Double getT1350() {
    return this.t1350;
  }

  public void setT1350(Double t1350) {
    this.t1350 = t1350;
  }

  public Double getT1355() {
    return this.t1355;
  }

  public void setT1355(Double t1355) {
    this.t1355 = t1355;
  }

  public Double getT1400() {
    return this.t1400;
  }

  public void setT1400(Double t1400) {
    this.t1400 = t1400;
  }

  public Double getT1405() {
    return this.t1405;
  }

  public void setT1405(Double t1405) {
    this.t1405 = t1405;
  }

  public Double getT1410() {
    return this.t1410;
  }

  public void setT1410(Double t1410) {
    this.t1410 = t1410;
  }

  public Double getT1415() {
    return this.t1415;
  }

  public void setT1415(Double t1415) {
    this.t1415 = t1415;
  }

  public Double getT1420() {
    return this.t1420;
  }

  public void setT1420(Double t1420) {
    this.t1420 = t1420;
  }

  public Double getT1425() {
    return this.t1425;
  }

  public void setT1425(Double t1425) {
    this.t1425 = t1425;
  }

  public Double getT1430() {
    return this.t1430;
  }

  public void setT1430(Double t1430) {
    this.t1430 = t1430;
  }

  public Double getT1435() {
    return this.t1435;
  }

  public void setT1435(Double t1435) {
    this.t1435 = t1435;
  }

  public Double getT1440() {
    return this.t1440;
  }

  public void setT1440(Double t1440) {
    this.t1440 = t1440;
  }

  public Double getT1445() {
    return this.t1445;
  }

  public void setT1445(Double t1445) {
    this.t1445 = t1445;
  }

  public Double getT1450() {
    return this.t1450;
  }

  public void setT1450(Double t1450) {
    this.t1450 = t1450;
  }

  public Double getT1455() {
    return this.t1455;
  }

  public void setT1455(Double t1455) {
    this.t1455 = t1455;
  }

  public Double getT1500() {
    return this.t1500;
  }

  public void setT1500(Double t1500) {
    this.t1500 = t1500;
  }

  public Double getT1505() {
    return this.t1505;
  }

  public void setT1505(Double t1505) {
    this.t1505 = t1505;
  }

  public Double getT1510() {
    return this.t1510;
  }

  public void setT1510(Double t1510) {
    this.t1510 = t1510;
  }

  public Double getT1515() {
    return this.t1515;
  }

  public void setT1515(Double t1515) {
    this.t1515 = t1515;
  }

  public Double getT1520() {
    return this.t1520;
  }

  public void setT1520(Double t1520) {
    this.t1520 = t1520;
  }

  public Double getT1525() {
    return this.t1525;
  }

  public void setT1525(Double t1525) {
    this.t1525 = t1525;
  }

  public Double getT1530() {
    return this.t1530;
  }

  public void setT1530(Double t1530) {
    this.t1530 = t1530;
  }

  public Double getT1535() {
    return this.t1535;
  }

  public void setT1535(Double t1535) {
    this.t1535 = t1535;
  }

  public Double getT1540() {
    return this.t1540;
  }

  public void setT1540(Double t1540) {
    this.t1540 = t1540;
  }

  public Double getT1545() {
    return this.t1545;
  }

  public void setT1545(Double t1545) {
    this.t1545 = t1545;
  }

  public Double getT1550() {
    return this.t1550;
  }

  public void setT1550(Double t1550) {
    this.t1550 = t1550;
  }

  public Double getT1555() {
    return this.t1555;
  }

  public void setT1555(Double t1555) {
    this.t1555 = t1555;
  }

  public Double getT1600() {
    return this.t1600;
  }

  public void setT1600(Double t1600) {
    this.t1600 = t1600;
  }

  public Double getT1605() {
    return this.t1605;
  }

  public void setT1605(Double t1605) {
    this.t1605 = t1605;
  }

  public Double getT1610() {
    return this.t1610;
  }

  public void setT1610(Double t1610) {
    this.t1610 = t1610;
  }

  public Double getT1615() {
    return this.t1615;
  }

  public void setT1615(Double t1615) {
    this.t1615 = t1615;
  }

  public Double getT1620() {
    return this.t1620;
  }

  public void setT1620(Double t1620) {
    this.t1620 = t1620;
  }

  public Double getT1625() {
    return this.t1625;
  }

  public void setT1625(Double t1625) {
    this.t1625 = t1625;
  }

  public Double getT1630() {
    return this.t1630;
  }

  public void setT1630(Double t1630) {
    this.t1630 = t1630;
  }

  public Double getT1635() {
    return this.t1635;
  }

  public void setT1635(Double t1635) {
    this.t1635 = t1635;
  }

  public Double getT1640() {
    return this.t1640;
  }

  public void setT1640(Double t1640) {
    this.t1640 = t1640;
  }

  public Double getT1645() {
    return this.t1645;
  }

  public void setT1645(Double t1645) {
    this.t1645 = t1645;
  }

  public Double getT1650() {
    return this.t1650;
  }

  public void setT1650(Double t1650) {
    this.t1650 = t1650;
  }

  public Double getT1655() {
    return this.t1655;
  }

  public void setT1655(Double t1655) {
    this.t1655 = t1655;
  }

  public Double getT1700() {
    return this.t1700;
  }

  public void setT1700(Double t1700) {
    this.t1700 = t1700;
  }

  public Double getT1705() {
    return this.t1705;
  }

  public void setT1705(Double t1705) {
    this.t1705 = t1705;
  }

  public Double getT1710() {
    return this.t1710;
  }

  public void setT1710(Double t1710) {
    this.t1710 = t1710;
  }

  public Double getT1715() {
    return this.t1715;
  }

  public void setT1715(Double t1715) {
    this.t1715 = t1715;
  }

  public Double getT1720() {
    return this.t1720;
  }

  public void setT1720(Double t1720) {
    this.t1720 = t1720;
  }

  public Double getT1725() {
    return this.t1725;
  }

  public void setT1725(Double t1725) {
    this.t1725 = t1725;
  }

  public Double getT1730() {
    return this.t1730;
  }

  public void setT1730(Double t1730) {
    this.t1730 = t1730;
  }

  public Double getT1735() {
    return this.t1735;
  }

  public void setT1735(Double t1735) {
    this.t1735 = t1735;
  }

  public Double getT1740() {
    return this.t1740;
  }

  public void setT1740(Double t1740) {
    this.t1740 = t1740;
  }

  public Double getT1745() {
    return this.t1745;
  }

  public void setT1745(Double t1745) {
    this.t1745 = t1745;
  }

  public Double getT1750() {
    return this.t1750;
  }

  public void setT1750(Double t1750) {
    this.t1750 = t1750;
  }

  public Double getT1755() {
    return this.t1755;
  }

  public void setT1755(Double t1755) {
    this.t1755 = t1755;
  }

  public Double getT1800() {
    return this.t1800;
  }

  public void setT1800(Double t1800) {
    this.t1800 = t1800;
  }

  public Double getT1805() {
    return this.t1805;
  }

  public void setT1805(Double t1805) {
    this.t1805 = t1805;
  }

  public Double getT1810() {
    return this.t1810;
  }

  public void setT1810(Double t1810) {
    this.t1810 = t1810;
  }

  public Double getT1815() {
    return this.t1815;
  }

  public void setT1815(Double t1815) {
    this.t1815 = t1815;
  }

  public Double getT1820() {
    return this.t1820;
  }

  public void setT1820(Double t1820) {
    this.t1820 = t1820;
  }

  public Double getT1825() {
    return this.t1825;
  }

  public void setT1825(Double t1825) {
    this.t1825 = t1825;
  }

  public Double getT1830() {
    return this.t1830;
  }

  public void setT1830(Double t1830) {
    this.t1830 = t1830;
  }

  public Double getT1835() {
    return this.t1835;
  }

  public void setT1835(Double t1835) {
    this.t1835 = t1835;
  }

  public Double getT1840() {
    return this.t1840;
  }

  public void setT1840(Double t1840) {
    this.t1840 = t1840;
  }

  public Double getT1845() {
    return this.t1845;
  }

  public void setT1845(Double t1845) {
    this.t1845 = t1845;
  }

  public Double getT1850() {
    return this.t1850;
  }

  public void setT1850(Double t1850) {
    this.t1850 = t1850;
  }

  public Double getT1855() {
    return this.t1855;
  }

  public void setT1855(Double t1855) {
    this.t1855 = t1855;
  }

  public Double getT1900() {
    return this.t1900;
  }

  public void setT1900(Double t1900) {
    this.t1900 = t1900;
  }

  public Double getT1905() {
    return this.t1905;
  }

  public void setT1905(Double t1905) {
    this.t1905 = t1905;
  }

  public Double getT1910() {
    return this.t1910;
  }

  public void setT1910(Double t1910) {
    this.t1910 = t1910;
  }

  public Double getT1915() {
    return this.t1915;
  }

  public void setT1915(Double t1915) {
    this.t1915 = t1915;
  }

  public Double getT1920() {
    return this.t1920;
  }

  public void setT1920(Double t1920) {
    this.t1920 = t1920;
  }

  public Double getT1925() {
    return this.t1925;
  }

  public void setT1925(Double t1925) {
    this.t1925 = t1925;
  }

  public Double getT1930() {
    return this.t1930;
  }

  public void setT1930(Double t1930) {
    this.t1930 = t1930;
  }

  public Double getT1935() {
    return this.t1935;
  }

  public void setT1935(Double t1935) {
    this.t1935 = t1935;
  }

  public Double getT1940() {
    return this.t1940;
  }

  public void setT1940(Double t1940) {
    this.t1940 = t1940;
  }

  public Double getT1945() {
    return this.t1945;
  }

  public void setT1945(Double t1945) {
    this.t1945 = t1945;
  }

  public Double getT1950() {
    return this.t1950;
  }

  public void setT1950(Double t1950) {
    this.t1950 = t1950;
  }

  public Double getT1955() {
    return this.t1955;
  }

  public void setT1955(Double t1955) {
    this.t1955 = t1955;
  }

  public Double getT2000() {
    return this.t2000;
  }

  public void setT2000(Double t2000) {
    this.t2000 = t2000;
  }

  public Double getT2005() {
    return this.t2005;
  }

  public void setT2005(Double t2005) {
    this.t2005 = t2005;
  }

  public Double getT2010() {
    return this.t2010;
  }

  public void setT2010(Double t2010) {
    this.t2010 = t2010;
  }

  public Double getT2015() {
    return this.t2015;
  }

  public void setT2015(Double t2015) {
    this.t2015 = t2015;
  }

  public Double getT2020() {
    return this.t2020;
  }

  public void setT2020(Double t2020) {
    this.t2020 = t2020;
  }

  public Double getT2025() {
    return this.t2025;
  }

  public void setT2025(Double t2025) {
    this.t2025 = t2025;
  }

  public Double getT2030() {
    return this.t2030;
  }

  public void setT2030(Double t2030) {
    this.t2030 = t2030;
  }

  public Double getT2035() {
    return this.t2035;
  }

  public void setT2035(Double t2035) {
    this.t2035 = t2035;
  }

  public Double getT2040() {
    return this.t2040;
  }

  public void setT2040(Double t2040) {
    this.t2040 = t2040;
  }

  public Double getT2045() {
    return this.t2045;
  }

  public void setT2045(Double t2045) {
    this.t2045 = t2045;
  }

  public Double getT2050() {
    return this.t2050;
  }

  public void setT2050(Double t2050) {
    this.t2050 = t2050;
  }

  public Double getT2055() {
    return this.t2055;
  }

  public void setT2055(Double t2055) {
    this.t2055 = t2055;
  }

  public Double getT2100() {
    return this.t2100;
  }

  public void setT2100(Double t2100) {
    this.t2100 = t2100;
  }

  public Double getT2105() {
    return this.t2105;
  }

  public void setT2105(Double t2105) {
    this.t2105 = t2105;
  }

  public Double getT2110() {
    return this.t2110;
  }

  public void setT2110(Double t2110) {
    this.t2110 = t2110;
  }

  public Double getT2115() {
    return this.t2115;
  }

  public void setT2115(Double t2115) {
    this.t2115 = t2115;
  }

  public Double getT2120() {
    return this.t2120;
  }

  public void setT2120(Double t2120) {
    this.t2120 = t2120;
  }

  public Double getT2125() {
    return this.t2125;
  }

  public void setT2125(Double t2125) {
    this.t2125 = t2125;
  }

  public Double getT2130() {
    return this.t2130;
  }

  public void setT2130(Double t2130) {
    this.t2130 = t2130;
  }

  public Double getT2135() {
    return this.t2135;
  }

  public void setT2135(Double t2135) {
    this.t2135 = t2135;
  }

  public Double getT2140() {
    return this.t2140;
  }

  public void setT2140(Double t2140) {
    this.t2140 = t2140;
  }

  public Double getT2145() {
    return this.t2145;
  }

  public void setT2145(Double t2145) {
    this.t2145 = t2145;
  }

  public Double getT2150() {
    return this.t2150;
  }

  public void setT2150(Double t2150) {
    this.t2150 = t2150;
  }

  public Double getT2155() {
    return this.t2155;
  }

  public void setT2155(Double t2155) {
    this.t2155 = t2155;
  }

  public Double getT2200() {
    return this.t2200;
  }

  public void setT2200(Double t2200) {
    this.t2200 = t2200;
  }

  public Double getT2205() {
    return this.t2205;
  }

  public void setT2205(Double t2205) {
    this.t2205 = t2205;
  }

  public Double getT2210() {
    return this.t2210;
  }

  public void setT2210(Double t2210) {
    this.t2210 = t2210;
  }

  public Double getT2215() {
    return this.t2215;
  }

  public void setT2215(Double t2215) {
    this.t2215 = t2215;
  }

  public Double getT2220() {
    return this.t2220;
  }

  public void setT2220(Double t2220) {
    this.t2220 = t2220;
  }

  public Double getT2225() {
    return this.t2225;
  }

  public void setT2225(Double t2225) {
    this.t2225 = t2225;
  }

  public Double getT2230() {
    return this.t2230;
  }

  public void setT2230(Double t2230) {
    this.t2230 = t2230;
  }

  public Double getT2235() {
    return this.t2235;
  }

  public void setT2235(Double t2235) {
    this.t2235 = t2235;
  }

  public Double getT2240() {
    return this.t2240;
  }

  public void setT2240(Double t2240) {
    this.t2240 = t2240;
  }

  public Double getT2245() {
    return this.t2245;
  }

  public void setT2245(Double t2245) {
    this.t2245 = t2245;
  }

  public Double getT2250() {
    return this.t2250;
  }

  public void setT2250(Double t2250) {
    this.t2250 = t2250;
  }

  public Double getT2255() {
    return this.t2255;
  }

  public void setT2255(Double t2255) {
    this.t2255 = t2255;
  }

  public Double getT2300() {
    return this.t2300;
  }

  public void setT2300(Double t2300) {
    this.t2300 = t2300;
  }

  public Double getT2305() {
    return this.t2305;
  }

  public void setT2305(Double t2305) {
    this.t2305 = t2305;
  }

  public Double getT2310() {
    return this.t2310;
  }

  public void setT2310(Double t2310) {
    this.t2310 = t2310;
  }

  public Double getT2315() {
    return this.t2315;
  }

  public void setT2315(Double t2315) {
    this.t2315 = t2315;
  }

  public Double getT2320() {
    return this.t2320;
  }

  public void setT2320(Double t2320) {
    this.t2320 = t2320;
  }

  public Double getT2325() {
    return this.t2325;
  }

  public void setT2325(Double t2325) {
    this.t2325 = t2325;
  }

  public Double getT2330() {
    return this.t2330;
  }

  public void setT2330(Double t2330) {
    this.t2330 = t2330;
  }

  public Double getT2335() {
    return this.t2335;
  }

  public void setT2335(Double t2335) {
    this.t2335 = t2335;
  }

  public Double getT2340() {
    return this.t2340;
  }

  public void setT2340(Double t2340) {
    this.t2340 = t2340;
  }

  public Double getT2345() {
    return this.t2345;
  }

  public void setT2345(Double t2345) {
    this.t2345 = t2345;
  }

  public Double getT2350() {
    return this.t2350;
  }

  public void setT2350(Double t2350) {
    this.t2350 = t2350;
  }

  public Double getT2355() {
    return this.t2355;
  }

  public void setT2355(Double t2355) {
    this.t2355 = t2355;
  }

}
