package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

/**
 * KwhBoundaries generated by hbm2java
 */
public class KwhBoundaries implements java.io.Serializable {

  private KwhBoundariesId id;
  private Equipment equipment;
  private Double minCons0000;
  private Double minCons0015;
  private Double minCons0030;
  private Double minCons0045;
  private Double minCons0100;
  private Double minCons0115;
  private Double minCons0130;
  private Double minCons0145;
  private Double minCons0200;
  private Double minCons0215;
  private Double minCons0230;
  private Double minCons0245;
  private Double minCons0300;
  private Double minCons0315;
  private Double minCons0330;
  private Double minCons0345;
  private Double minCons0400;
  private Double minCons0415;
  private Double minCons0430;
  private Double minCons0445;
  private Double minCons0500;
  private Double minCons0515;
  private Double minCons0530;
  private Double minCons0545;
  private Double minCons0600;
  private Double minCons0615;
  private Double minCons0630;
  private Double minCons0645;
  private Double minCons0700;
  private Double minCons0715;
  private Double minCons0730;
  private Double minCons0745;
  private Double minCons0800;
  private Double minCons0815;
  private Double minCons0830;
  private Double minCons0845;
  private Double minCons0900;
  private Double minCons0915;
  private Double minCons0930;
  private Double minCons0945;
  private Double minCons1000;
  private Double minCons1015;
  private Double minCons1030;
  private Double minCons1045;
  private Double minCons1100;
  private Double minCons1115;
  private Double minCons1130;
  private Double minCons1145;
  private Double minCons1200;
  private Double minCons1215;
  private Double minCons1230;
  private Double minCons1245;
  private Double minCons1300;
  private Double minCons1315;
  private Double minCons1330;
  private Double minCons1345;
  private Double minCons1400;
  private Double minCons1415;
  private Double minCons1430;
  private Double minCons1445;
  private Double minCons1500;
  private Double minCons1515;
  private Double minCons1530;
  private Double minCons1545;
  private Double minCons1600;
  private Double minCons1615;
  private Double minCons1630;
  private Double minCons1645;
  private Double minCons1700;
  private Double minCons1715;
  private Double minCons1730;
  private Double minCons1745;
  private Double minCons1800;
  private Double minCons1815;
  private Double minCons1830;
  private Double minCons1845;
  private Double minCons1900;
  private Double minCons1915;
  private Double minCons1930;
  private Double minCons1945;
  private Double minCons2000;
  private Double minCons2015;
  private Double minCons2030;
  private Double minCons2045;
  private Double minCons2100;
  private Double minCons2115;
  private Double minCons2130;
  private Double minCons2145;
  private Double minCons2200;
  private Double minCons2215;
  private Double minCons2230;
  private Double minCons2245;
  private Double minCons2300;
  private Double minCons2315;
  private Double minCons2330;
  private Double minCons2345;
  private Double maxCons0000;
  private Double maxCons0030;
  private Double maxCons0100;
  private Double maxCons0130;
  private Double maxCons0200;
  private Double maxCons0230;
  private Double maxCons0300;
  private Double maxCons0330;
  private Double maxCons0400;
  private Double maxCons0430;
  private Double maxCons0500;
  private Double maxCons0530;
  private Double maxCons0600;
  private Double maxCons0630;
  private Double maxCons0700;
  private Double maxCons0730;
  private Double maxCons0800;
  private Double maxCons0830;
  private Double maxCons0900;
  private Double maxCons0930;
  private Double maxCons1000;
  private Double maxCons1030;
  private Double maxCons1100;
  private Double maxCons1130;
  private Double maxCons1200;
  private Double maxCons1230;
  private Double maxCons1300;
  private Double maxCons1330;
  private Double maxCons1400;
  private Double maxCons1430;
  private Double maxCons1500;
  private Double maxCons1530;
  private Double maxCons1600;
  private Double maxCons1630;
  private Double maxCons1700;
  private Double maxCons1730;
  private Double maxCons1800;
  private Double maxCons1830;
  private Double maxCons1900;
  private Double maxCons1930;
  private Double maxCons2000;
  private Double maxCons2030;
  private Double maxCons2100;
  private Double maxCons2130;
  private Double maxCons2200;
  private Double maxCons2230;
  private Double maxCons2300;
  private Double maxCons2330;

  public KwhBoundaries() {
  }

  public KwhBoundaries(KwhBoundariesId id, Equipment equipment) {
    this.id = id;
    this.equipment = equipment;
  }

  public KwhBoundaries(KwhBoundariesId id, Equipment equipment, Double minCons0000, Double minCons0015, Double minCons0030,
      Double minCons0045, Double minCons0100, Double minCons0115, Double minCons0130, Double minCons0145, Double minCons0200,
      Double minCons0215, Double minCons0230, Double minCons0245, Double minCons0300, Double minCons0315, Double minCons0330,
      Double minCons0345, Double minCons0400, Double minCons0415, Double minCons0430, Double minCons0445, Double minCons0500,
      Double minCons0515, Double minCons0530, Double minCons0545, Double minCons0600, Double minCons0615, Double minCons0630,
      Double minCons0645, Double minCons0700, Double minCons0715, Double minCons0730, Double minCons0745, Double minCons0800,
      Double minCons0815, Double minCons0830, Double minCons0845, Double minCons0900, Double minCons0915, Double minCons0930,
      Double minCons0945, Double minCons1000, Double minCons1015, Double minCons1030, Double minCons1045, Double minCons1100,
      Double minCons1115, Double minCons1130, Double minCons1145, Double minCons1200, Double minCons1215, Double minCons1230,
      Double minCons1245, Double minCons1300, Double minCons1315, Double minCons1330, Double minCons1345, Double minCons1400,
      Double minCons1415, Double minCons1430, Double minCons1445, Double minCons1500, Double minCons1515, Double minCons1530,
      Double minCons1545, Double minCons1600, Double minCons1615, Double minCons1630, Double minCons1645, Double minCons1700,
      Double minCons1715, Double minCons1730, Double minCons1745, Double minCons1800, Double minCons1815, Double minCons1830,
      Double minCons1845, Double minCons1900, Double minCons1915, Double minCons1930, Double minCons1945, Double minCons2000,
      Double minCons2015, Double minCons2030, Double minCons2045, Double minCons2100, Double minCons2115, Double minCons2130,
      Double minCons2145, Double minCons2200, Double minCons2215, Double minCons2230, Double minCons2245, Double minCons2300,
      Double minCons2315, Double minCons2330, Double minCons2345, Double maxCons0000, Double maxCons0030, Double maxCons0100,
      Double maxCons0130, Double maxCons0200, Double maxCons0230, Double maxCons0300, Double maxCons0330, Double maxCons0400,
      Double maxCons0430, Double maxCons0500, Double maxCons0530, Double maxCons0600, Double maxCons0630, Double maxCons0700,
      Double maxCons0730, Double maxCons0800, Double maxCons0830, Double maxCons0900, Double maxCons0930, Double maxCons1000,
      Double maxCons1030, Double maxCons1100, Double maxCons1130, Double maxCons1200, Double maxCons1230, Double maxCons1300,
      Double maxCons1330, Double maxCons1400, Double maxCons1430, Double maxCons1500, Double maxCons1530, Double maxCons1600,
      Double maxCons1630, Double maxCons1700, Double maxCons1730, Double maxCons1800, Double maxCons1830, Double maxCons1900,
      Double maxCons1930, Double maxCons2000, Double maxCons2030, Double maxCons2100, Double maxCons2130, Double maxCons2200,
      Double maxCons2230, Double maxCons2300, Double maxCons2330) {
    this.id = id;
    this.equipment = equipment;
    this.minCons0000 = minCons0000;
    this.minCons0015 = minCons0015;
    this.minCons0030 = minCons0030;
    this.minCons0045 = minCons0045;
    this.minCons0100 = minCons0100;
    this.minCons0115 = minCons0115;
    this.minCons0130 = minCons0130;
    this.minCons0145 = minCons0145;
    this.minCons0200 = minCons0200;
    this.minCons0215 = minCons0215;
    this.minCons0230 = minCons0230;
    this.minCons0245 = minCons0245;
    this.minCons0300 = minCons0300;
    this.minCons0315 = minCons0315;
    this.minCons0330 = minCons0330;
    this.minCons0345 = minCons0345;
    this.minCons0400 = minCons0400;
    this.minCons0415 = minCons0415;
    this.minCons0430 = minCons0430;
    this.minCons0445 = minCons0445;
    this.minCons0500 = minCons0500;
    this.minCons0515 = minCons0515;
    this.minCons0530 = minCons0530;
    this.minCons0545 = minCons0545;
    this.minCons0600 = minCons0600;
    this.minCons0615 = minCons0615;
    this.minCons0630 = minCons0630;
    this.minCons0645 = minCons0645;
    this.minCons0700 = minCons0700;
    this.minCons0715 = minCons0715;
    this.minCons0730 = minCons0730;
    this.minCons0745 = minCons0745;
    this.minCons0800 = minCons0800;
    this.minCons0815 = minCons0815;
    this.minCons0830 = minCons0830;
    this.minCons0845 = minCons0845;
    this.minCons0900 = minCons0900;
    this.minCons0915 = minCons0915;
    this.minCons0930 = minCons0930;
    this.minCons0945 = minCons0945;
    this.minCons1000 = minCons1000;
    this.minCons1015 = minCons1015;
    this.minCons1030 = minCons1030;
    this.minCons1045 = minCons1045;
    this.minCons1100 = minCons1100;
    this.minCons1115 = minCons1115;
    this.minCons1130 = minCons1130;
    this.minCons1145 = minCons1145;
    this.minCons1200 = minCons1200;
    this.minCons1215 = minCons1215;
    this.minCons1230 = minCons1230;
    this.minCons1245 = minCons1245;
    this.minCons1300 = minCons1300;
    this.minCons1315 = minCons1315;
    this.minCons1330 = minCons1330;
    this.minCons1345 = minCons1345;
    this.minCons1400 = minCons1400;
    this.minCons1415 = minCons1415;
    this.minCons1430 = minCons1430;
    this.minCons1445 = minCons1445;
    this.minCons1500 = minCons1500;
    this.minCons1515 = minCons1515;
    this.minCons1530 = minCons1530;
    this.minCons1545 = minCons1545;
    this.minCons1600 = minCons1600;
    this.minCons1615 = minCons1615;
    this.minCons1630 = minCons1630;
    this.minCons1645 = minCons1645;
    this.minCons1700 = minCons1700;
    this.minCons1715 = minCons1715;
    this.minCons1730 = minCons1730;
    this.minCons1745 = minCons1745;
    this.minCons1800 = minCons1800;
    this.minCons1815 = minCons1815;
    this.minCons1830 = minCons1830;
    this.minCons1845 = minCons1845;
    this.minCons1900 = minCons1900;
    this.minCons1915 = minCons1915;
    this.minCons1930 = minCons1930;
    this.minCons1945 = minCons1945;
    this.minCons2000 = minCons2000;
    this.minCons2015 = minCons2015;
    this.minCons2030 = minCons2030;
    this.minCons2045 = minCons2045;
    this.minCons2100 = minCons2100;
    this.minCons2115 = minCons2115;
    this.minCons2130 = minCons2130;
    this.minCons2145 = minCons2145;
    this.minCons2200 = minCons2200;
    this.minCons2215 = minCons2215;
    this.minCons2230 = minCons2230;
    this.minCons2245 = minCons2245;
    this.minCons2300 = minCons2300;
    this.minCons2315 = minCons2315;
    this.minCons2330 = minCons2330;
    this.minCons2345 = minCons2345;
    this.maxCons0000 = maxCons0000;
    this.maxCons0030 = maxCons0030;
    this.maxCons0100 = maxCons0100;
    this.maxCons0130 = maxCons0130;
    this.maxCons0200 = maxCons0200;
    this.maxCons0230 = maxCons0230;
    this.maxCons0300 = maxCons0300;
    this.maxCons0330 = maxCons0330;
    this.maxCons0400 = maxCons0400;
    this.maxCons0430 = maxCons0430;
    this.maxCons0500 = maxCons0500;
    this.maxCons0530 = maxCons0530;
    this.maxCons0600 = maxCons0600;
    this.maxCons0630 = maxCons0630;
    this.maxCons0700 = maxCons0700;
    this.maxCons0730 = maxCons0730;
    this.maxCons0800 = maxCons0800;
    this.maxCons0830 = maxCons0830;
    this.maxCons0900 = maxCons0900;
    this.maxCons0930 = maxCons0930;
    this.maxCons1000 = maxCons1000;
    this.maxCons1030 = maxCons1030;
    this.maxCons1100 = maxCons1100;
    this.maxCons1130 = maxCons1130;
    this.maxCons1200 = maxCons1200;
    this.maxCons1230 = maxCons1230;
    this.maxCons1300 = maxCons1300;
    this.maxCons1330 = maxCons1330;
    this.maxCons1400 = maxCons1400;
    this.maxCons1430 = maxCons1430;
    this.maxCons1500 = maxCons1500;
    this.maxCons1530 = maxCons1530;
    this.maxCons1600 = maxCons1600;
    this.maxCons1630 = maxCons1630;
    this.maxCons1700 = maxCons1700;
    this.maxCons1730 = maxCons1730;
    this.maxCons1800 = maxCons1800;
    this.maxCons1830 = maxCons1830;
    this.maxCons1900 = maxCons1900;
    this.maxCons1930 = maxCons1930;
    this.maxCons2000 = maxCons2000;
    this.maxCons2030 = maxCons2030;
    this.maxCons2100 = maxCons2100;
    this.maxCons2130 = maxCons2130;
    this.maxCons2200 = maxCons2200;
    this.maxCons2230 = maxCons2230;
    this.maxCons2300 = maxCons2300;
    this.maxCons2330 = maxCons2330;
  }

  public KwhBoundariesId getId() {
    return this.id;
  }

  public void setId(KwhBoundariesId id) {
    this.id = id;
  }

  public Equipment getEquipment() {
    return this.equipment;
  }

  public void setEquipment(Equipment equipment) {
    this.equipment = equipment;
  }

  public Double getMinCons0000() {
    return this.minCons0000;
  }

  public void setMinCons0000(Double minCons0000) {
    this.minCons0000 = minCons0000;
  }

  public Double getMinCons0015() {
    return this.minCons0015;
  }

  public void setMinCons0015(Double minCons0015) {
    this.minCons0015 = minCons0015;
  }

  public Double getMinCons0030() {
    return this.minCons0030;
  }

  public void setMinCons0030(Double minCons0030) {
    this.minCons0030 = minCons0030;
  }

  public Double getMinCons0045() {
    return this.minCons0045;
  }

  public void setMinCons0045(Double minCons0045) {
    this.minCons0045 = minCons0045;
  }

  public Double getMinCons0100() {
    return this.minCons0100;
  }

  public void setMinCons0100(Double minCons0100) {
    this.minCons0100 = minCons0100;
  }

  public Double getMinCons0115() {
    return this.minCons0115;
  }

  public void setMinCons0115(Double minCons0115) {
    this.minCons0115 = minCons0115;
  }

  public Double getMinCons0130() {
    return this.minCons0130;
  }

  public void setMinCons0130(Double minCons0130) {
    this.minCons0130 = minCons0130;
  }

  public Double getMinCons0145() {
    return this.minCons0145;
  }

  public void setMinCons0145(Double minCons0145) {
    this.minCons0145 = minCons0145;
  }

  public Double getMinCons0200() {
    return this.minCons0200;
  }

  public void setMinCons0200(Double minCons0200) {
    this.minCons0200 = minCons0200;
  }

  public Double getMinCons0215() {
    return this.minCons0215;
  }

  public void setMinCons0215(Double minCons0215) {
    this.minCons0215 = minCons0215;
  }

  public Double getMinCons0230() {
    return this.minCons0230;
  }

  public void setMinCons0230(Double minCons0230) {
    this.minCons0230 = minCons0230;
  }

  public Double getMinCons0245() {
    return this.minCons0245;
  }

  public void setMinCons0245(Double minCons0245) {
    this.minCons0245 = minCons0245;
  }

  public Double getMinCons0300() {
    return this.minCons0300;
  }

  public void setMinCons0300(Double minCons0300) {
    this.minCons0300 = minCons0300;
  }

  public Double getMinCons0315() {
    return this.minCons0315;
  }

  public void setMinCons0315(Double minCons0315) {
    this.minCons0315 = minCons0315;
  }

  public Double getMinCons0330() {
    return this.minCons0330;
  }

  public void setMinCons0330(Double minCons0330) {
    this.minCons0330 = minCons0330;
  }

  public Double getMinCons0345() {
    return this.minCons0345;
  }

  public void setMinCons0345(Double minCons0345) {
    this.minCons0345 = minCons0345;
  }

  public Double getMinCons0400() {
    return this.minCons0400;
  }

  public void setMinCons0400(Double minCons0400) {
    this.minCons0400 = minCons0400;
  }

  public Double getMinCons0415() {
    return this.minCons0415;
  }

  public void setMinCons0415(Double minCons0415) {
    this.minCons0415 = minCons0415;
  }

  public Double getMinCons0430() {
    return this.minCons0430;
  }

  public void setMinCons0430(Double minCons0430) {
    this.minCons0430 = minCons0430;
  }

  public Double getMinCons0445() {
    return this.minCons0445;
  }

  public void setMinCons0445(Double minCons0445) {
    this.minCons0445 = minCons0445;
  }

  public Double getMinCons0500() {
    return this.minCons0500;
  }

  public void setMinCons0500(Double minCons0500) {
    this.minCons0500 = minCons0500;
  }

  public Double getMinCons0515() {
    return this.minCons0515;
  }

  public void setMinCons0515(Double minCons0515) {
    this.minCons0515 = minCons0515;
  }

  public Double getMinCons0530() {
    return this.minCons0530;
  }

  public void setMinCons0530(Double minCons0530) {
    this.minCons0530 = minCons0530;
  }

  public Double getMinCons0545() {
    return this.minCons0545;
  }

  public void setMinCons0545(Double minCons0545) {
    this.minCons0545 = minCons0545;
  }

  public Double getMinCons0600() {
    return this.minCons0600;
  }

  public void setMinCons0600(Double minCons0600) {
    this.minCons0600 = minCons0600;
  }

  public Double getMinCons0615() {
    return this.minCons0615;
  }

  public void setMinCons0615(Double minCons0615) {
    this.minCons0615 = minCons0615;
  }

  public Double getMinCons0630() {
    return this.minCons0630;
  }

  public void setMinCons0630(Double minCons0630) {
    this.minCons0630 = minCons0630;
  }

  public Double getMinCons0645() {
    return this.minCons0645;
  }

  public void setMinCons0645(Double minCons0645) {
    this.minCons0645 = minCons0645;
  }

  public Double getMinCons0700() {
    return this.minCons0700;
  }

  public void setMinCons0700(Double minCons0700) {
    this.minCons0700 = minCons0700;
  }

  public Double getMinCons0715() {
    return this.minCons0715;
  }

  public void setMinCons0715(Double minCons0715) {
    this.minCons0715 = minCons0715;
  }

  public Double getMinCons0730() {
    return this.minCons0730;
  }

  public void setMinCons0730(Double minCons0730) {
    this.minCons0730 = minCons0730;
  }

  public Double getMinCons0745() {
    return this.minCons0745;
  }

  public void setMinCons0745(Double minCons0745) {
    this.minCons0745 = minCons0745;
  }

  public Double getMinCons0800() {
    return this.minCons0800;
  }

  public void setMinCons0800(Double minCons0800) {
    this.minCons0800 = minCons0800;
  }

  public Double getMinCons0815() {
    return this.minCons0815;
  }

  public void setMinCons0815(Double minCons0815) {
    this.minCons0815 = minCons0815;
  }

  public Double getMinCons0830() {
    return this.minCons0830;
  }

  public void setMinCons0830(Double minCons0830) {
    this.minCons0830 = minCons0830;
  }

  public Double getMinCons0845() {
    return this.minCons0845;
  }

  public void setMinCons0845(Double minCons0845) {
    this.minCons0845 = minCons0845;
  }

  public Double getMinCons0900() {
    return this.minCons0900;
  }

  public void setMinCons0900(Double minCons0900) {
    this.minCons0900 = minCons0900;
  }

  public Double getMinCons0915() {
    return this.minCons0915;
  }

  public void setMinCons0915(Double minCons0915) {
    this.minCons0915 = minCons0915;
  }

  public Double getMinCons0930() {
    return this.minCons0930;
  }

  public void setMinCons0930(Double minCons0930) {
    this.minCons0930 = minCons0930;
  }

  public Double getMinCons0945() {
    return this.minCons0945;
  }

  public void setMinCons0945(Double minCons0945) {
    this.minCons0945 = minCons0945;
  }

  public Double getMinCons1000() {
    return this.minCons1000;
  }

  public void setMinCons1000(Double minCons1000) {
    this.minCons1000 = minCons1000;
  }

  public Double getMinCons1015() {
    return this.minCons1015;
  }

  public void setMinCons1015(Double minCons1015) {
    this.minCons1015 = minCons1015;
  }

  public Double getMinCons1030() {
    return this.minCons1030;
  }

  public void setMinCons1030(Double minCons1030) {
    this.minCons1030 = minCons1030;
  }

  public Double getMinCons1045() {
    return this.minCons1045;
  }

  public void setMinCons1045(Double minCons1045) {
    this.minCons1045 = minCons1045;
  }

  public Double getMinCons1100() {
    return this.minCons1100;
  }

  public void setMinCons1100(Double minCons1100) {
    this.minCons1100 = minCons1100;
  }

  public Double getMinCons1115() {
    return this.minCons1115;
  }

  public void setMinCons1115(Double minCons1115) {
    this.minCons1115 = minCons1115;
  }

  public Double getMinCons1130() {
    return this.minCons1130;
  }

  public void setMinCons1130(Double minCons1130) {
    this.minCons1130 = minCons1130;
  }

  public Double getMinCons1145() {
    return this.minCons1145;
  }

  public void setMinCons1145(Double minCons1145) {
    this.minCons1145 = minCons1145;
  }

  public Double getMinCons1200() {
    return this.minCons1200;
  }

  public void setMinCons1200(Double minCons1200) {
    this.minCons1200 = minCons1200;
  }

  public Double getMinCons1215() {
    return this.minCons1215;
  }

  public void setMinCons1215(Double minCons1215) {
    this.minCons1215 = minCons1215;
  }

  public Double getMinCons1230() {
    return this.minCons1230;
  }

  public void setMinCons1230(Double minCons1230) {
    this.minCons1230 = minCons1230;
  }

  public Double getMinCons1245() {
    return this.minCons1245;
  }

  public void setMinCons1245(Double minCons1245) {
    this.minCons1245 = minCons1245;
  }

  public Double getMinCons1300() {
    return this.minCons1300;
  }

  public void setMinCons1300(Double minCons1300) {
    this.minCons1300 = minCons1300;
  }

  public Double getMinCons1315() {
    return this.minCons1315;
  }

  public void setMinCons1315(Double minCons1315) {
    this.minCons1315 = minCons1315;
  }

  public Double getMinCons1330() {
    return this.minCons1330;
  }

  public void setMinCons1330(Double minCons1330) {
    this.minCons1330 = minCons1330;
  }

  public Double getMinCons1345() {
    return this.minCons1345;
  }

  public void setMinCons1345(Double minCons1345) {
    this.minCons1345 = minCons1345;
  }

  public Double getMinCons1400() {
    return this.minCons1400;
  }

  public void setMinCons1400(Double minCons1400) {
    this.minCons1400 = minCons1400;
  }

  public Double getMinCons1415() {
    return this.minCons1415;
  }

  public void setMinCons1415(Double minCons1415) {
    this.minCons1415 = minCons1415;
  }

  public Double getMinCons1430() {
    return this.minCons1430;
  }

  public void setMinCons1430(Double minCons1430) {
    this.minCons1430 = minCons1430;
  }

  public Double getMinCons1445() {
    return this.minCons1445;
  }

  public void setMinCons1445(Double minCons1445) {
    this.minCons1445 = minCons1445;
  }

  public Double getMinCons1500() {
    return this.minCons1500;
  }

  public void setMinCons1500(Double minCons1500) {
    this.minCons1500 = minCons1500;
  }

  public Double getMinCons1515() {
    return this.minCons1515;
  }

  public void setMinCons1515(Double minCons1515) {
    this.minCons1515 = minCons1515;
  }

  public Double getMinCons1530() {
    return this.minCons1530;
  }

  public void setMinCons1530(Double minCons1530) {
    this.minCons1530 = minCons1530;
  }

  public Double getMinCons1545() {
    return this.minCons1545;
  }

  public void setMinCons1545(Double minCons1545) {
    this.minCons1545 = minCons1545;
  }

  public Double getMinCons1600() {
    return this.minCons1600;
  }

  public void setMinCons1600(Double minCons1600) {
    this.minCons1600 = minCons1600;
  }

  public Double getMinCons1615() {
    return this.minCons1615;
  }

  public void setMinCons1615(Double minCons1615) {
    this.minCons1615 = minCons1615;
  }

  public Double getMinCons1630() {
    return this.minCons1630;
  }

  public void setMinCons1630(Double minCons1630) {
    this.minCons1630 = minCons1630;
  }

  public Double getMinCons1645() {
    return this.minCons1645;
  }

  public void setMinCons1645(Double minCons1645) {
    this.minCons1645 = minCons1645;
  }

  public Double getMinCons1700() {
    return this.minCons1700;
  }

  public void setMinCons1700(Double minCons1700) {
    this.minCons1700 = minCons1700;
  }

  public Double getMinCons1715() {
    return this.minCons1715;
  }

  public void setMinCons1715(Double minCons1715) {
    this.minCons1715 = minCons1715;
  }

  public Double getMinCons1730() {
    return this.minCons1730;
  }

  public void setMinCons1730(Double minCons1730) {
    this.minCons1730 = minCons1730;
  }

  public Double getMinCons1745() {
    return this.minCons1745;
  }

  public void setMinCons1745(Double minCons1745) {
    this.minCons1745 = minCons1745;
  }

  public Double getMinCons1800() {
    return this.minCons1800;
  }

  public void setMinCons1800(Double minCons1800) {
    this.minCons1800 = minCons1800;
  }

  public Double getMinCons1815() {
    return this.minCons1815;
  }

  public void setMinCons1815(Double minCons1815) {
    this.minCons1815 = minCons1815;
  }

  public Double getMinCons1830() {
    return this.minCons1830;
  }

  public void setMinCons1830(Double minCons1830) {
    this.minCons1830 = minCons1830;
  }

  public Double getMinCons1845() {
    return this.minCons1845;
  }

  public void setMinCons1845(Double minCons1845) {
    this.minCons1845 = minCons1845;
  }

  public Double getMinCons1900() {
    return this.minCons1900;
  }

  public void setMinCons1900(Double minCons1900) {
    this.minCons1900 = minCons1900;
  }

  public Double getMinCons1915() {
    return this.minCons1915;
  }

  public void setMinCons1915(Double minCons1915) {
    this.minCons1915 = minCons1915;
  }

  public Double getMinCons1930() {
    return this.minCons1930;
  }

  public void setMinCons1930(Double minCons1930) {
    this.minCons1930 = minCons1930;
  }

  public Double getMinCons1945() {
    return this.minCons1945;
  }

  public void setMinCons1945(Double minCons1945) {
    this.minCons1945 = minCons1945;
  }

  public Double getMinCons2000() {
    return this.minCons2000;
  }

  public void setMinCons2000(Double minCons2000) {
    this.minCons2000 = minCons2000;
  }

  public Double getMinCons2015() {
    return this.minCons2015;
  }

  public void setMinCons2015(Double minCons2015) {
    this.minCons2015 = minCons2015;
  }

  public Double getMinCons2030() {
    return this.minCons2030;
  }

  public void setMinCons2030(Double minCons2030) {
    this.minCons2030 = minCons2030;
  }

  public Double getMinCons2045() {
    return this.minCons2045;
  }

  public void setMinCons2045(Double minCons2045) {
    this.minCons2045 = minCons2045;
  }

  public Double getMinCons2100() {
    return this.minCons2100;
  }

  public void setMinCons2100(Double minCons2100) {
    this.minCons2100 = minCons2100;
  }

  public Double getMinCons2115() {
    return this.minCons2115;
  }

  public void setMinCons2115(Double minCons2115) {
    this.minCons2115 = minCons2115;
  }

  public Double getMinCons2130() {
    return this.minCons2130;
  }

  public void setMinCons2130(Double minCons2130) {
    this.minCons2130 = minCons2130;
  }

  public Double getMinCons2145() {
    return this.minCons2145;
  }

  public void setMinCons2145(Double minCons2145) {
    this.minCons2145 = minCons2145;
  }

  public Double getMinCons2200() {
    return this.minCons2200;
  }

  public void setMinCons2200(Double minCons2200) {
    this.minCons2200 = minCons2200;
  }

  public Double getMinCons2215() {
    return this.minCons2215;
  }

  public void setMinCons2215(Double minCons2215) {
    this.minCons2215 = minCons2215;
  }

  public Double getMinCons2230() {
    return this.minCons2230;
  }

  public void setMinCons2230(Double minCons2230) {
    this.minCons2230 = minCons2230;
  }

  public Double getMinCons2245() {
    return this.minCons2245;
  }

  public void setMinCons2245(Double minCons2245) {
    this.minCons2245 = minCons2245;
  }

  public Double getMinCons2300() {
    return this.minCons2300;
  }

  public void setMinCons2300(Double minCons2300) {
    this.minCons2300 = minCons2300;
  }

  public Double getMinCons2315() {
    return this.minCons2315;
  }

  public void setMinCons2315(Double minCons2315) {
    this.minCons2315 = minCons2315;
  }

  public Double getMinCons2330() {
    return this.minCons2330;
  }

  public void setMinCons2330(Double minCons2330) {
    this.minCons2330 = minCons2330;
  }

  public Double getMinCons2345() {
    return this.minCons2345;
  }

  public void setMinCons2345(Double minCons2345) {
    this.minCons2345 = minCons2345;
  }

  public Double getMaxCons0000() {
    return this.maxCons0000;
  }

  public void setMaxCons0000(Double maxCons0000) {
    this.maxCons0000 = maxCons0000;
  }

  public Double getMaxCons0030() {
    return this.maxCons0030;
  }

  public void setMaxCons0030(Double maxCons0030) {
    this.maxCons0030 = maxCons0030;
  }

  public Double getMaxCons0100() {
    return this.maxCons0100;
  }

  public void setMaxCons0100(Double maxCons0100) {
    this.maxCons0100 = maxCons0100;
  }

  public Double getMaxCons0130() {
    return this.maxCons0130;
  }

  public void setMaxCons0130(Double maxCons0130) {
    this.maxCons0130 = maxCons0130;
  }

  public Double getMaxCons0200() {
    return this.maxCons0200;
  }

  public void setMaxCons0200(Double maxCons0200) {
    this.maxCons0200 = maxCons0200;
  }

  public Double getMaxCons0230() {
    return this.maxCons0230;
  }

  public void setMaxCons0230(Double maxCons0230) {
    this.maxCons0230 = maxCons0230;
  }

  public Double getMaxCons0300() {
    return this.maxCons0300;
  }

  public void setMaxCons0300(Double maxCons0300) {
    this.maxCons0300 = maxCons0300;
  }

  public Double getMaxCons0330() {
    return this.maxCons0330;
  }

  public void setMaxCons0330(Double maxCons0330) {
    this.maxCons0330 = maxCons0330;
  }

  public Double getMaxCons0400() {
    return this.maxCons0400;
  }

  public void setMaxCons0400(Double maxCons0400) {
    this.maxCons0400 = maxCons0400;
  }

  public Double getMaxCons0430() {
    return this.maxCons0430;
  }

  public void setMaxCons0430(Double maxCons0430) {
    this.maxCons0430 = maxCons0430;
  }

  public Double getMaxCons0500() {
    return this.maxCons0500;
  }

  public void setMaxCons0500(Double maxCons0500) {
    this.maxCons0500 = maxCons0500;
  }

  public Double getMaxCons0530() {
    return this.maxCons0530;
  }

  public void setMaxCons0530(Double maxCons0530) {
    this.maxCons0530 = maxCons0530;
  }

  public Double getMaxCons0600() {
    return this.maxCons0600;
  }

  public void setMaxCons0600(Double maxCons0600) {
    this.maxCons0600 = maxCons0600;
  }

  public Double getMaxCons0630() {
    return this.maxCons0630;
  }

  public void setMaxCons0630(Double maxCons0630) {
    this.maxCons0630 = maxCons0630;
  }

  public Double getMaxCons0700() {
    return this.maxCons0700;
  }

  public void setMaxCons0700(Double maxCons0700) {
    this.maxCons0700 = maxCons0700;
  }

  public Double getMaxCons0730() {
    return this.maxCons0730;
  }

  public void setMaxCons0730(Double maxCons0730) {
    this.maxCons0730 = maxCons0730;
  }

  public Double getMaxCons0800() {
    return this.maxCons0800;
  }

  public void setMaxCons0800(Double maxCons0800) {
    this.maxCons0800 = maxCons0800;
  }

  public Double getMaxCons0830() {
    return this.maxCons0830;
  }

  public void setMaxCons0830(Double maxCons0830) {
    this.maxCons0830 = maxCons0830;
  }

  public Double getMaxCons0900() {
    return this.maxCons0900;
  }

  public void setMaxCons0900(Double maxCons0900) {
    this.maxCons0900 = maxCons0900;
  }

  public Double getMaxCons0930() {
    return this.maxCons0930;
  }

  public void setMaxCons0930(Double maxCons0930) {
    this.maxCons0930 = maxCons0930;
  }

  public Double getMaxCons1000() {
    return this.maxCons1000;
  }

  public void setMaxCons1000(Double maxCons1000) {
    this.maxCons1000 = maxCons1000;
  }

  public Double getMaxCons1030() {
    return this.maxCons1030;
  }

  public void setMaxCons1030(Double maxCons1030) {
    this.maxCons1030 = maxCons1030;
  }

  public Double getMaxCons1100() {
    return this.maxCons1100;
  }

  public void setMaxCons1100(Double maxCons1100) {
    this.maxCons1100 = maxCons1100;
  }

  public Double getMaxCons1130() {
    return this.maxCons1130;
  }

  public void setMaxCons1130(Double maxCons1130) {
    this.maxCons1130 = maxCons1130;
  }

  public Double getMaxCons1200() {
    return this.maxCons1200;
  }

  public void setMaxCons1200(Double maxCons1200) {
    this.maxCons1200 = maxCons1200;
  }

  public Double getMaxCons1230() {
    return this.maxCons1230;
  }

  public void setMaxCons1230(Double maxCons1230) {
    this.maxCons1230 = maxCons1230;
  }

  public Double getMaxCons1300() {
    return this.maxCons1300;
  }

  public void setMaxCons1300(Double maxCons1300) {
    this.maxCons1300 = maxCons1300;
  }

  public Double getMaxCons1330() {
    return this.maxCons1330;
  }

  public void setMaxCons1330(Double maxCons1330) {
    this.maxCons1330 = maxCons1330;
  }

  public Double getMaxCons1400() {
    return this.maxCons1400;
  }

  public void setMaxCons1400(Double maxCons1400) {
    this.maxCons1400 = maxCons1400;
  }

  public Double getMaxCons1430() {
    return this.maxCons1430;
  }

  public void setMaxCons1430(Double maxCons1430) {
    this.maxCons1430 = maxCons1430;
  }

  public Double getMaxCons1500() {
    return this.maxCons1500;
  }

  public void setMaxCons1500(Double maxCons1500) {
    this.maxCons1500 = maxCons1500;
  }

  public Double getMaxCons1530() {
    return this.maxCons1530;
  }

  public void setMaxCons1530(Double maxCons1530) {
    this.maxCons1530 = maxCons1530;
  }

  public Double getMaxCons1600() {
    return this.maxCons1600;
  }

  public void setMaxCons1600(Double maxCons1600) {
    this.maxCons1600 = maxCons1600;
  }

  public Double getMaxCons1630() {
    return this.maxCons1630;
  }

  public void setMaxCons1630(Double maxCons1630) {
    this.maxCons1630 = maxCons1630;
  }

  public Double getMaxCons1700() {
    return this.maxCons1700;
  }

  public void setMaxCons1700(Double maxCons1700) {
    this.maxCons1700 = maxCons1700;
  }

  public Double getMaxCons1730() {
    return this.maxCons1730;
  }

  public void setMaxCons1730(Double maxCons1730) {
    this.maxCons1730 = maxCons1730;
  }

  public Double getMaxCons1800() {
    return this.maxCons1800;
  }

  public void setMaxCons1800(Double maxCons1800) {
    this.maxCons1800 = maxCons1800;
  }

  public Double getMaxCons1830() {
    return this.maxCons1830;
  }

  public void setMaxCons1830(Double maxCons1830) {
    this.maxCons1830 = maxCons1830;
  }

  public Double getMaxCons1900() {
    return this.maxCons1900;
  }

  public void setMaxCons1900(Double maxCons1900) {
    this.maxCons1900 = maxCons1900;
  }

  public Double getMaxCons1930() {
    return this.maxCons1930;
  }

  public void setMaxCons1930(Double maxCons1930) {
    this.maxCons1930 = maxCons1930;
  }

  public Double getMaxCons2000() {
    return this.maxCons2000;
  }

  public void setMaxCons2000(Double maxCons2000) {
    this.maxCons2000 = maxCons2000;
  }

  public Double getMaxCons2030() {
    return this.maxCons2030;
  }

  public void setMaxCons2030(Double maxCons2030) {
    this.maxCons2030 = maxCons2030;
  }

  public Double getMaxCons2100() {
    return this.maxCons2100;
  }

  public void setMaxCons2100(Double maxCons2100) {
    this.maxCons2100 = maxCons2100;
  }

  public Double getMaxCons2130() {
    return this.maxCons2130;
  }

  public void setMaxCons2130(Double maxCons2130) {
    this.maxCons2130 = maxCons2130;
  }

  public Double getMaxCons2200() {
    return this.maxCons2200;
  }

  public void setMaxCons2200(Double maxCons2200) {
    this.maxCons2200 = maxCons2200;
  }

  public Double getMaxCons2230() {
    return this.maxCons2230;
  }

  public void setMaxCons2230(Double maxCons2230) {
    this.maxCons2230 = maxCons2230;
  }

  public Double getMaxCons2300() {
    return this.maxCons2300;
  }

  public void setMaxCons2300(Double maxCons2300) {
    this.maxCons2300 = maxCons2300;
  }

  public Double getMaxCons2330() {
    return this.maxCons2330;
  }

  public void setMaxCons2330(Double maxCons2330) {
    this.maxCons2330 = maxCons2330;
  }

}
