package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

import org.joda.time.DateTime;

/**
 * KwhBoundariesId generated by hbm2java
 */
public class KwhBoundariesId implements java.io.Serializable {

  private DateTime dateCreation;
  private int weekday;
  private int equipmentId;

  public KwhBoundariesId() {
  }

  public KwhBoundariesId(DateTime dateCreation, int weekday, int equipmentId) {
    this.dateCreation = dateCreation;
    this.weekday = weekday;
    this.equipmentId = equipmentId;
  }

  public DateTime getDateCreation() {
    return this.dateCreation;
  }

  public void setDateCreation(DateTime dateCreation) {
    this.dateCreation = dateCreation;
  }

  public int getWeekday() {
    return this.weekday;
  }

  public void setWeekday(int weekday) {
    this.weekday = weekday;
  }

  public int getEquipmentId() {
    return this.equipmentId;
  }

  public void setEquipmentId(int equipmentId) {
    this.equipmentId = equipmentId;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof KwhBoundariesId))
      return false;
    KwhBoundariesId castOther = (KwhBoundariesId) other;

    return ((this.getDateCreation() == castOther.getDateCreation()) || (this.getDateCreation() != null
        && castOther.getDateCreation() != null && this.getDateCreation().equals(castOther.getDateCreation())))
        && (this.getWeekday() == castOther.getWeekday()) && (this.getEquipmentId() == castOther.getEquipmentId());
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (getDateCreation() == null ? 0 : this.getDateCreation().hashCode());
    result = 37 * result + this.getWeekday();
    result = 37 * result + this.getEquipmentId();
    return result;
  }

}
