package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

import org.joda.time.DateTime;

/**
 * KwhForecastId generated by hbm2java
 */
public class KwhForecastId implements java.io.Serializable {

  private DateTime dateForecast;
  private int equipmentId;
  private String parameterType;

  public KwhForecastId() {
  }

  public KwhForecastId(DateTime dateForecast, int equipmentId, String parameterType) {
    this.dateForecast = dateForecast;
    this.equipmentId = equipmentId;
    this.parameterType = parameterType;
  }

  public DateTime getDateForecast() {
    return this.dateForecast;
  }

  public void setDateForecast(DateTime dateForecast) {
    this.dateForecast = dateForecast;
  }

  public int getEquipmentId() {
    return this.equipmentId;
  }

  public void setEquipmentId(int equipmentId) {
    this.equipmentId = equipmentId;
  }

  public String getParameterType() {
    return this.parameterType;
  }

  public void setParameterType(String parameterType) {
    this.parameterType = parameterType;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof KwhForecastId))
      return false;
    KwhForecastId castOther = (KwhForecastId) other;

    return ((this.getDateForecast() == castOther.getDateForecast()) || (this.getDateForecast() != null
        && castOther.getDateForecast() != null && this.getDateForecast().equals(castOther.getDateForecast())))
        && (this.getEquipmentId() == castOther.getEquipmentId())
        && ((this.getParameterType() == castOther.getParameterType()) || (this.getParameterType() != null
            && castOther.getParameterType() != null && this.getParameterType().equals(castOther.getParameterType())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (getDateForecast() == null ? 0 : this.getDateForecast().hashCode());
    result = 37 * result + this.getEquipmentId();
    result = 37 * result + (getParameterType() == null ? 0 : this.getParameterType().hashCode());
    return result;
  }

}
