package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

/**
 * KwhHourly generated by hbm2java
 */
public class KwhHourly implements java.io.Serializable {

  private KwhHourlyId id;
  private Equipment equipment;
  private Double t0000;
  private Double t0100;
  private Double t0200;
  private Double t0300;
  private Double t0400;
  private Double t0500;
  private Double t0600;
  private Double t0700;
  private Double t0800;
  private Double t0900;
  private Double t1000;
  private Double t1100;
  private Double t1200;
  private Double t1300;
  private Double t1400;
  private Double t1500;
  private Double t1600;
  private Double t1700;
  private Double t1800;
  private Double t1900;
  private Double t2000;
  private Double t2100;
  private Double t2200;
  private Double t2300;

  public KwhHourly() {
  }

  public KwhHourly(KwhHourlyId id, Equipment equipment) {
    this.id = id;
    this.equipment = equipment;
  }

  public KwhHourly(KwhHourlyId id, Equipment equipment, Double t0000, Double t0100, Double t0200, Double t0300, Double t0400,
      Double t0500, Double t0600, Double t0700, Double t0800, Double t0900, Double t1000, Double t1100, Double t1200,
      Double t1300, Double t1400, Double t1500, Double t1600, Double t1700, Double t1800, Double t1900, Double t2000,
      Double t2100, Double t2200, Double t2300) {
    this.id = id;
    this.equipment = equipment;
    this.t0000 = t0000;
    this.t0100 = t0100;
    this.t0200 = t0200;
    this.t0300 = t0300;
    this.t0400 = t0400;
    this.t0500 = t0500;
    this.t0600 = t0600;
    this.t0700 = t0700;
    this.t0800 = t0800;
    this.t0900 = t0900;
    this.t1000 = t1000;
    this.t1100 = t1100;
    this.t1200 = t1200;
    this.t1300 = t1300;
    this.t1400 = t1400;
    this.t1500 = t1500;
    this.t1600 = t1600;
    this.t1700 = t1700;
    this.t1800 = t1800;
    this.t1900 = t1900;
    this.t2000 = t2000;
    this.t2100 = t2100;
    this.t2200 = t2200;
    this.t2300 = t2300;
  }

  public KwhHourlyId getId() {
    return this.id;
  }

  public void setId(KwhHourlyId id) {
    this.id = id;
  }

  public Equipment getEquipment() {
    return this.equipment;
  }

  public void setEquipment(Equipment equipment) {
    this.equipment = equipment;
  }

  public Double getT0000() {
    return this.t0000;
  }

  public void setT0000(Double t0000) {
    this.t0000 = t0000;
  }

  public Double getT0100() {
    return this.t0100;
  }

  public void setT0100(Double t0100) {
    this.t0100 = t0100;
  }

  public Double getT0200() {
    return this.t0200;
  }

  public void setT0200(Double t0200) {
    this.t0200 = t0200;
  }

  public Double getT0300() {
    return this.t0300;
  }

  public void setT0300(Double t0300) {
    this.t0300 = t0300;
  }

  public Double getT0400() {
    return this.t0400;
  }

  public void setT0400(Double t0400) {
    this.t0400 = t0400;
  }

  public Double getT0500() {
    return this.t0500;
  }

  public void setT0500(Double t0500) {
    this.t0500 = t0500;
  }

  public Double getT0600() {
    return this.t0600;
  }

  public void setT0600(Double t0600) {
    this.t0600 = t0600;
  }

  public Double getT0700() {
    return this.t0700;
  }

  public void setT0700(Double t0700) {
    this.t0700 = t0700;
  }

  public Double getT0800() {
    return this.t0800;
  }

  public void setT0800(Double t0800) {
    this.t0800 = t0800;
  }

  public Double getT0900() {
    return this.t0900;
  }

  public void setT0900(Double t0900) {
    this.t0900 = t0900;
  }

  public Double getT1000() {
    return this.t1000;
  }

  public void setT1000(Double t1000) {
    this.t1000 = t1000;
  }

  public Double getT1100() {
    return this.t1100;
  }

  public void setT1100(Double t1100) {
    this.t1100 = t1100;
  }

  public Double getT1200() {
    return this.t1200;
  }

  public void setT1200(Double t1200) {
    this.t1200 = t1200;
  }

  public Double getT1300() {
    return this.t1300;
  }

  public void setT1300(Double t1300) {
    this.t1300 = t1300;
  }

  public Double getT1400() {
    return this.t1400;
  }

  public void setT1400(Double t1400) {
    this.t1400 = t1400;
  }

  public Double getT1500() {
    return this.t1500;
  }

  public void setT1500(Double t1500) {
    this.t1500 = t1500;
  }

  public Double getT1600() {
    return this.t1600;
  }

  public void setT1600(Double t1600) {
    this.t1600 = t1600;
  }

  public Double getT1700() {
    return this.t1700;
  }

  public void setT1700(Double t1700) {
    this.t1700 = t1700;
  }

  public Double getT1800() {
    return this.t1800;
  }

  public void setT1800(Double t1800) {
    this.t1800 = t1800;
  }

  public Double getT1900() {
    return this.t1900;
  }

  public void setT1900(Double t1900) {
    this.t1900 = t1900;
  }

  public Double getT2000() {
    return this.t2000;
  }

  public void setT2000(Double t2000) {
    this.t2000 = t2000;
  }

  public Double getT2100() {
    return this.t2100;
  }

  public void setT2100(Double t2100) {
    this.t2100 = t2100;
  }

  public Double getT2200() {
    return this.t2200;
  }

  public void setT2200(Double t2200) {
    this.t2200 = t2200;
  }

  public Double getT2300() {
    return this.t2300;
  }

  public void setT2300(Double t2300) {
    this.t2300 = t2300;
  }

}
