package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

/**
 * OperatingStateId generated by hbm2java
 */
public class OperatingStateId implements java.io.Serializable {

  private int state;
  private int equipmentId;

  public OperatingStateId() {
  }

  public OperatingStateId(int state, int equipmentId) {
    this.state = state;
    this.equipmentId = equipmentId;
  }

  public int getState() {
    return this.state;
  }

  public void setState(int state) {
    this.state = state;
  }

  public int getEquipmentId() {
    return this.equipmentId;
  }

  public void setEquipmentId(int equipmentId) {
    this.equipmentId = equipmentId;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof OperatingStateId))
      return false;
    OperatingStateId castOther = (OperatingStateId) other;

    return (this.getState() == castOther.getState()) && (this.getEquipmentId() == castOther.getEquipmentId());
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + this.getState();
    result = 37 * result + this.getEquipmentId();
    return result;
  }

}
