package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

/**
 * OperatingState generated by hbm2java
 */
public class OperatingState implements java.io.Serializable {

  private OperatingStateId id;
  private Equipment equipment;
  private Double kw;

  public OperatingState() {
  }

  public OperatingState(OperatingStateId id, Equipment equipment) {
    this.id = id;
    this.equipment = equipment;
  }

  public OperatingState(OperatingStateId id, Equipment equipment, Double kw) {
    this.id = id;
    this.equipment = equipment;
    this.kw = kw;
  }

  public OperatingStateId getId() {
    return this.id;
  }

  public void setId(OperatingStateId id) {
    this.id = id;
  }

  public Equipment getEquipment() {
    return this.equipment;
  }

  public void setEquipment(Equipment equipment) {
    this.equipment = equipment;
  }

  public Double getKw() {
    return this.kw;
  }

  public void setKw(Double kw) {
    this.kw = kw;
  }

}
