package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

/**
 * PlanHasActionId generated by hbm2java
 */
public class PlanHasActionId implements java.io.Serializable {

  private int planId;
  private int actionId;

  public PlanHasActionId() {
  }

  public PlanHasActionId(int planId, int actionId) {
    this.planId = planId;
    this.actionId = actionId;
  }

  public int getPlanId() {
    return this.planId;
  }

  public void setPlanId(int planId) {
    this.planId = planId;
  }

  public int getActionId() {
    return this.actionId;
  }

  public void setActionId(int actionId) {
    this.actionId = actionId;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof PlanHasActionId))
      return false;
    PlanHasActionId castOther = (PlanHasActionId) other;

    return (this.getPlanId() == castOther.getPlanId()) && (this.getActionId() == castOther.getActionId());
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + this.getPlanId();
    result = 37 * result + this.getActionId();
    return result;
  }

}
