package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

/**
 * PlanWeightId generated by hbm2java
 */
public class PlanWeightId implements java.io.Serializable {

  private int planId;
  private String actionAttributeName;

  public PlanWeightId() {
  }

  public PlanWeightId(int planId, String actionAttributeName) {
    this.planId = planId;
    this.actionAttributeName = actionAttributeName;
  }

  public int getPlanId() {
    return this.planId;
  }

  public void setPlanId(int planId) {
    this.planId = planId;
  }

  public String getActionAttributeName() {
    return this.actionAttributeName;
  }

  public void setActionAttributeName(String actionAttributeName) {
    this.actionAttributeName = actionAttributeName;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof PlanWeightId))
      return false;
    PlanWeightId castOther = (PlanWeightId) other;

    return (this.getPlanId() == castOther.getPlanId())
        && ((this.getActionAttributeName() == castOther.getActionAttributeName()) || (this.getActionAttributeName() != null
            && castOther.getActionAttributeName() != null && this.getActionAttributeName().equals(
            castOther.getActionAttributeName())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + this.getPlanId();
    result = 37 * result + (getActionAttributeName() == null ? 0 : this.getActionAttributeName().hashCode());
    return result;
  }

}
