package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

/**
 * ProsumerHasSiteId generated by hbm2java
 */
public class ProsumerHasSiteId implements java.io.Serializable {

  private int prosumerId;
  private int siteId;

  public ProsumerHasSiteId() {
  }

  public ProsumerHasSiteId(int prosumerId, int siteId) {
    this.prosumerId = prosumerId;
    this.siteId = siteId;
  }

  public int getProsumerId() {
    return this.prosumerId;
  }

  public void setProsumerId(int prosumerId) {
    this.prosumerId = prosumerId;
  }

  public int getSiteId() {
    return this.siteId;
  }

  public void setSiteId(int siteId) {
    this.siteId = siteId;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof ProsumerHasSiteId))
      return false;
    ProsumerHasSiteId castOther = (ProsumerHasSiteId) other;

    return (this.getProsumerId() == castOther.getProsumerId()) && (this.getSiteId() == castOther.getSiteId());
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + this.getProsumerId();
    result = 37 * result + this.getSiteId();
    return result;
  }

}
