package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

/**
 * ProsumerPreference generated by hbm2java
 */
public class ProsumerPreference implements java.io.Serializable {

  private int actionId;
  private Action action;
  private Integer priority;
  private Double pumin0000;
  private Double pumin0015;
  private Double pumin0030;
  private Double pumin0045;
  private Double pumin0100;
  private Double pumin0115;
  private Double pumin0130;
  private Double pumin0145;
  private Double pumin0200;
  private Double pumin0215;
  private Double pumin0230;
  private Double pumin0245;
  private Double pumin0300;
  private Double pumin0315;
  private Double pumin0330;
  private Double pumin0345;
  private Double pumin0400;
  private Double pumin0415;
  private Double pumin0430;
  private Double pumin0445;
  private Double pumin0500;
  private Double pumin0515;
  private Double pumin0530;
  private Double pumin0545;
  private Double pumin0600;
  private Double pumin0615;
  private Double pumin0630;
  private Double pumin0645;
  private Double pumin0700;
  private Double pumin0715;
  private Double pumin0730;
  private Double pumin0745;
  private Double pumin0800;
  private Double pumin0815;
  private Double pumin0830;
  private Double pumin0845;
  private Double pumin0900;
  private Double pumin0915;
  private Double pumin0930;
  private Double pumin0945;
  private Double pumin1000;
  private Double pumin1015;
  private Double pumin1030;
  private Double pumin1045;
  private Double pumin1100;
  private Double pumin1115;
  private Double pumin1130;
  private Double pumin1145;
  private Double pumin1200;
  private Double pumin1215;
  private Double pumin1230;
  private Double pumin1245;
  private Double pumin1300;
  private Double pumin1315;
  private Double pumin1330;
  private Double pumin1345;
  private Double pumin1400;
  private Double pumin1415;
  private Double pumin1430;
  private Double pumin1445;
  private Double pumin1500;
  private Double pumin1515;
  private Double pumin1530;
  private Double pumin1545;
  private Double pumin1600;
  private Double pumin1615;
  private Double pumin1630;
  private Double pumin1645;
  private Double pumin1700;
  private Double pumin1715;
  private Double pumin1730;
  private Double pumin1745;
  private Double pumin1800;
  private Double pumin1815;
  private Double pumin1830;
  private Double pumin1845;
  private Double pumin1900;
  private Double pumin1915;
  private Double pumin1930;
  private Double pumin1945;
  private Double pumin2000;
  private Double pumin2015;
  private Double pumin2030;
  private Double pumin2045;
  private Double pumin2100;
  private Double pumin2115;
  private Double pumin2130;
  private Double pumin2145;
  private Double pumin2200;
  private Double pumin2215;
  private Double pumin2230;
  private Double pumin2245;
  private Double pumin2300;
  private Double pumin2315;
  private Double pumin2330;
  private Double pumin2345;

  public ProsumerPreference() {
  }

  public ProsumerPreference(Action action) {
    this.action = action;
  }

  public ProsumerPreference(Action action, Integer priority, Double pumin0000, Double pumin0015, Double pumin0030,
      Double pumin0045, Double pumin0100, Double pumin0115, Double pumin0130, Double pumin0145, Double pumin0200,
      Double pumin0215, Double pumin0230, Double pumin0245, Double pumin0300, Double pumin0315, Double pumin0330,
      Double pumin0345, Double pumin0400, Double pumin0415, Double pumin0430, Double pumin0445, Double pumin0500,
      Double pumin0515, Double pumin0530, Double pumin0545, Double pumin0600, Double pumin0615, Double pumin0630,
      Double pumin0645, Double pumin0700, Double pumin0715, Double pumin0730, Double pumin0745, Double pumin0800,
      Double pumin0815, Double pumin0830, Double pumin0845, Double pumin0900, Double pumin0915, Double pumin0930,
      Double pumin0945, Double pumin1000, Double pumin1015, Double pumin1030, Double pumin1045, Double pumin1100,
      Double pumin1115, Double pumin1130, Double pumin1145, Double pumin1200, Double pumin1215, Double pumin1230,
      Double pumin1245, Double pumin1300, Double pumin1315, Double pumin1330, Double pumin1345, Double pumin1400,
      Double pumin1415, Double pumin1430, Double pumin1445, Double pumin1500, Double pumin1515, Double pumin1530,
      Double pumin1545, Double pumin1600, Double pumin1615, Double pumin1630, Double pumin1645, Double pumin1700,
      Double pumin1715, Double pumin1730, Double pumin1745, Double pumin1800, Double pumin1815, Double pumin1830,
      Double pumin1845, Double pumin1900, Double pumin1915, Double pumin1930, Double pumin1945, Double pumin2000,
      Double pumin2015, Double pumin2030, Double pumin2045, Double pumin2100, Double pumin2115, Double pumin2130,
      Double pumin2145, Double pumin2200, Double pumin2215, Double pumin2230, Double pumin2245, Double pumin2300,
      Double pumin2315, Double pumin2330, Double pumin2345) {
    this.action = action;
    this.priority = priority;
    this.pumin0000 = pumin0000;
    this.pumin0015 = pumin0015;
    this.pumin0030 = pumin0030;
    this.pumin0045 = pumin0045;
    this.pumin0100 = pumin0100;
    this.pumin0115 = pumin0115;
    this.pumin0130 = pumin0130;
    this.pumin0145 = pumin0145;
    this.pumin0200 = pumin0200;
    this.pumin0215 = pumin0215;
    this.pumin0230 = pumin0230;
    this.pumin0245 = pumin0245;
    this.pumin0300 = pumin0300;
    this.pumin0315 = pumin0315;
    this.pumin0330 = pumin0330;
    this.pumin0345 = pumin0345;
    this.pumin0400 = pumin0400;
    this.pumin0415 = pumin0415;
    this.pumin0430 = pumin0430;
    this.pumin0445 = pumin0445;
    this.pumin0500 = pumin0500;
    this.pumin0515 = pumin0515;
    this.pumin0530 = pumin0530;
    this.pumin0545 = pumin0545;
    this.pumin0600 = pumin0600;
    this.pumin0615 = pumin0615;
    this.pumin0630 = pumin0630;
    this.pumin0645 = pumin0645;
    this.pumin0700 = pumin0700;
    this.pumin0715 = pumin0715;
    this.pumin0730 = pumin0730;
    this.pumin0745 = pumin0745;
    this.pumin0800 = pumin0800;
    this.pumin0815 = pumin0815;
    this.pumin0830 = pumin0830;
    this.pumin0845 = pumin0845;
    this.pumin0900 = pumin0900;
    this.pumin0915 = pumin0915;
    this.pumin0930 = pumin0930;
    this.pumin0945 = pumin0945;
    this.pumin1000 = pumin1000;
    this.pumin1015 = pumin1015;
    this.pumin1030 = pumin1030;
    this.pumin1045 = pumin1045;
    this.pumin1100 = pumin1100;
    this.pumin1115 = pumin1115;
    this.pumin1130 = pumin1130;
    this.pumin1145 = pumin1145;
    this.pumin1200 = pumin1200;
    this.pumin1215 = pumin1215;
    this.pumin1230 = pumin1230;
    this.pumin1245 = pumin1245;
    this.pumin1300 = pumin1300;
    this.pumin1315 = pumin1315;
    this.pumin1330 = pumin1330;
    this.pumin1345 = pumin1345;
    this.pumin1400 = pumin1400;
    this.pumin1415 = pumin1415;
    this.pumin1430 = pumin1430;
    this.pumin1445 = pumin1445;
    this.pumin1500 = pumin1500;
    this.pumin1515 = pumin1515;
    this.pumin1530 = pumin1530;
    this.pumin1545 = pumin1545;
    this.pumin1600 = pumin1600;
    this.pumin1615 = pumin1615;
    this.pumin1630 = pumin1630;
    this.pumin1645 = pumin1645;
    this.pumin1700 = pumin1700;
    this.pumin1715 = pumin1715;
    this.pumin1730 = pumin1730;
    this.pumin1745 = pumin1745;
    this.pumin1800 = pumin1800;
    this.pumin1815 = pumin1815;
    this.pumin1830 = pumin1830;
    this.pumin1845 = pumin1845;
    this.pumin1900 = pumin1900;
    this.pumin1915 = pumin1915;
    this.pumin1930 = pumin1930;
    this.pumin1945 = pumin1945;
    this.pumin2000 = pumin2000;
    this.pumin2015 = pumin2015;
    this.pumin2030 = pumin2030;
    this.pumin2045 = pumin2045;
    this.pumin2100 = pumin2100;
    this.pumin2115 = pumin2115;
    this.pumin2130 = pumin2130;
    this.pumin2145 = pumin2145;
    this.pumin2200 = pumin2200;
    this.pumin2215 = pumin2215;
    this.pumin2230 = pumin2230;
    this.pumin2245 = pumin2245;
    this.pumin2300 = pumin2300;
    this.pumin2315 = pumin2315;
    this.pumin2330 = pumin2330;
    this.pumin2345 = pumin2345;
  }

  public int getActionId() {
    return this.actionId;
  }

  public void setActionId(int actionId) {
    this.actionId = actionId;
  }

  public Action getAction() {
    return this.action;
  }

  public void setAction(Action action) {
    this.action = action;
  }

  public Integer getPriority() {
    return this.priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  public Double getPumin0000() {
    return this.pumin0000;
  }

  public void setPumin0000(Double pumin0000) {
    this.pumin0000 = pumin0000;
  }

  public Double getPumin0015() {
    return this.pumin0015;
  }

  public void setPumin0015(Double pumin0015) {
    this.pumin0015 = pumin0015;
  }

  public Double getPumin0030() {
    return this.pumin0030;
  }

  public void setPumin0030(Double pumin0030) {
    this.pumin0030 = pumin0030;
  }

  public Double getPumin0045() {
    return this.pumin0045;
  }

  public void setPumin0045(Double pumin0045) {
    this.pumin0045 = pumin0045;
  }

  public Double getPumin0100() {
    return this.pumin0100;
  }

  public void setPumin0100(Double pumin0100) {
    this.pumin0100 = pumin0100;
  }

  public Double getPumin0115() {
    return this.pumin0115;
  }

  public void setPumin0115(Double pumin0115) {
    this.pumin0115 = pumin0115;
  }

  public Double getPumin0130() {
    return this.pumin0130;
  }

  public void setPumin0130(Double pumin0130) {
    this.pumin0130 = pumin0130;
  }

  public Double getPumin0145() {
    return this.pumin0145;
  }

  public void setPumin0145(Double pumin0145) {
    this.pumin0145 = pumin0145;
  }

  public Double getPumin0200() {
    return this.pumin0200;
  }

  public void setPumin0200(Double pumin0200) {
    this.pumin0200 = pumin0200;
  }

  public Double getPumin0215() {
    return this.pumin0215;
  }

  public void setPumin0215(Double pumin0215) {
    this.pumin0215 = pumin0215;
  }

  public Double getPumin0230() {
    return this.pumin0230;
  }

  public void setPumin0230(Double pumin0230) {
    this.pumin0230 = pumin0230;
  }

  public Double getPumin0245() {
    return this.pumin0245;
  }

  public void setPumin0245(Double pumin0245) {
    this.pumin0245 = pumin0245;
  }

  public Double getPumin0300() {
    return this.pumin0300;
  }

  public void setPumin0300(Double pumin0300) {
    this.pumin0300 = pumin0300;
  }

  public Double getPumin0315() {
    return this.pumin0315;
  }

  public void setPumin0315(Double pumin0315) {
    this.pumin0315 = pumin0315;
  }

  public Double getPumin0330() {
    return this.pumin0330;
  }

  public void setPumin0330(Double pumin0330) {
    this.pumin0330 = pumin0330;
  }

  public Double getPumin0345() {
    return this.pumin0345;
  }

  public void setPumin0345(Double pumin0345) {
    this.pumin0345 = pumin0345;
  }

  public Double getPumin0400() {
    return this.pumin0400;
  }

  public void setPumin0400(Double pumin0400) {
    this.pumin0400 = pumin0400;
  }

  public Double getPumin0415() {
    return this.pumin0415;
  }

  public void setPumin0415(Double pumin0415) {
    this.pumin0415 = pumin0415;
  }

  public Double getPumin0430() {
    return this.pumin0430;
  }

  public void setPumin0430(Double pumin0430) {
    this.pumin0430 = pumin0430;
  }

  public Double getPumin0445() {
    return this.pumin0445;
  }

  public void setPumin0445(Double pumin0445) {
    this.pumin0445 = pumin0445;
  }

  public Double getPumin0500() {
    return this.pumin0500;
  }

  public void setPumin0500(Double pumin0500) {
    this.pumin0500 = pumin0500;
  }

  public Double getPumin0515() {
    return this.pumin0515;
  }

  public void setPumin0515(Double pumin0515) {
    this.pumin0515 = pumin0515;
  }

  public Double getPumin0530() {
    return this.pumin0530;
  }

  public void setPumin0530(Double pumin0530) {
    this.pumin0530 = pumin0530;
  }

  public Double getPumin0545() {
    return this.pumin0545;
  }

  public void setPumin0545(Double pumin0545) {
    this.pumin0545 = pumin0545;
  }

  public Double getPumin0600() {
    return this.pumin0600;
  }

  public void setPumin0600(Double pumin0600) {
    this.pumin0600 = pumin0600;
  }

  public Double getPumin0615() {
    return this.pumin0615;
  }

  public void setPumin0615(Double pumin0615) {
    this.pumin0615 = pumin0615;
  }

  public Double getPumin0630() {
    return this.pumin0630;
  }

  public void setPumin0630(Double pumin0630) {
    this.pumin0630 = pumin0630;
  }

  public Double getPumin0645() {
    return this.pumin0645;
  }

  public void setPumin0645(Double pumin0645) {
    this.pumin0645 = pumin0645;
  }

  public Double getPumin0700() {
    return this.pumin0700;
  }

  public void setPumin0700(Double pumin0700) {
    this.pumin0700 = pumin0700;
  }

  public Double getPumin0715() {
    return this.pumin0715;
  }

  public void setPumin0715(Double pumin0715) {
    this.pumin0715 = pumin0715;
  }

  public Double getPumin0730() {
    return this.pumin0730;
  }

  public void setPumin0730(Double pumin0730) {
    this.pumin0730 = pumin0730;
  }

  public Double getPumin0745() {
    return this.pumin0745;
  }

  public void setPumin0745(Double pumin0745) {
    this.pumin0745 = pumin0745;
  }

  public Double getPumin0800() {
    return this.pumin0800;
  }

  public void setPumin0800(Double pumin0800) {
    this.pumin0800 = pumin0800;
  }

  public Double getPumin0815() {
    return this.pumin0815;
  }

  public void setPumin0815(Double pumin0815) {
    this.pumin0815 = pumin0815;
  }

  public Double getPumin0830() {
    return this.pumin0830;
  }

  public void setPumin0830(Double pumin0830) {
    this.pumin0830 = pumin0830;
  }

  public Double getPumin0845() {
    return this.pumin0845;
  }

  public void setPumin0845(Double pumin0845) {
    this.pumin0845 = pumin0845;
  }

  public Double getPumin0900() {
    return this.pumin0900;
  }

  public void setPumin0900(Double pumin0900) {
    this.pumin0900 = pumin0900;
  }

  public Double getPumin0915() {
    return this.pumin0915;
  }

  public void setPumin0915(Double pumin0915) {
    this.pumin0915 = pumin0915;
  }

  public Double getPumin0930() {
    return this.pumin0930;
  }

  public void setPumin0930(Double pumin0930) {
    this.pumin0930 = pumin0930;
  }

  public Double getPumin0945() {
    return this.pumin0945;
  }

  public void setPumin0945(Double pumin0945) {
    this.pumin0945 = pumin0945;
  }

  public Double getPumin1000() {
    return this.pumin1000;
  }

  public void setPumin1000(Double pumin1000) {
    this.pumin1000 = pumin1000;
  }

  public Double getPumin1015() {
    return this.pumin1015;
  }

  public void setPumin1015(Double pumin1015) {
    this.pumin1015 = pumin1015;
  }

  public Double getPumin1030() {
    return this.pumin1030;
  }

  public void setPumin1030(Double pumin1030) {
    this.pumin1030 = pumin1030;
  }

  public Double getPumin1045() {
    return this.pumin1045;
  }

  public void setPumin1045(Double pumin1045) {
    this.pumin1045 = pumin1045;
  }

  public Double getPumin1100() {
    return this.pumin1100;
  }

  public void setPumin1100(Double pumin1100) {
    this.pumin1100 = pumin1100;
  }

  public Double getPumin1115() {
    return this.pumin1115;
  }

  public void setPumin1115(Double pumin1115) {
    this.pumin1115 = pumin1115;
  }

  public Double getPumin1130() {
    return this.pumin1130;
  }

  public void setPumin1130(Double pumin1130) {
    this.pumin1130 = pumin1130;
  }

  public Double getPumin1145() {
    return this.pumin1145;
  }

  public void setPumin1145(Double pumin1145) {
    this.pumin1145 = pumin1145;
  }

  public Double getPumin1200() {
    return this.pumin1200;
  }

  public void setPumin1200(Double pumin1200) {
    this.pumin1200 = pumin1200;
  }

  public Double getPumin1215() {
    return this.pumin1215;
  }

  public void setPumin1215(Double pumin1215) {
    this.pumin1215 = pumin1215;
  }

  public Double getPumin1230() {
    return this.pumin1230;
  }

  public void setPumin1230(Double pumin1230) {
    this.pumin1230 = pumin1230;
  }

  public Double getPumin1245() {
    return this.pumin1245;
  }

  public void setPumin1245(Double pumin1245) {
    this.pumin1245 = pumin1245;
  }

  public Double getPumin1300() {
    return this.pumin1300;
  }

  public void setPumin1300(Double pumin1300) {
    this.pumin1300 = pumin1300;
  }

  public Double getPumin1315() {
    return this.pumin1315;
  }

  public void setPumin1315(Double pumin1315) {
    this.pumin1315 = pumin1315;
  }

  public Double getPumin1330() {
    return this.pumin1330;
  }

  public void setPumin1330(Double pumin1330) {
    this.pumin1330 = pumin1330;
  }

  public Double getPumin1345() {
    return this.pumin1345;
  }

  public void setPumin1345(Double pumin1345) {
    this.pumin1345 = pumin1345;
  }

  public Double getPumin1400() {
    return this.pumin1400;
  }

  public void setPumin1400(Double pumin1400) {
    this.pumin1400 = pumin1400;
  }

  public Double getPumin1415() {
    return this.pumin1415;
  }

  public void setPumin1415(Double pumin1415) {
    this.pumin1415 = pumin1415;
  }

  public Double getPumin1430() {
    return this.pumin1430;
  }

  public void setPumin1430(Double pumin1430) {
    this.pumin1430 = pumin1430;
  }

  public Double getPumin1445() {
    return this.pumin1445;
  }

  public void setPumin1445(Double pumin1445) {
    this.pumin1445 = pumin1445;
  }

  public Double getPumin1500() {
    return this.pumin1500;
  }

  public void setPumin1500(Double pumin1500) {
    this.pumin1500 = pumin1500;
  }

  public Double getPumin1515() {
    return this.pumin1515;
  }

  public void setPumin1515(Double pumin1515) {
    this.pumin1515 = pumin1515;
  }

  public Double getPumin1530() {
    return this.pumin1530;
  }

  public void setPumin1530(Double pumin1530) {
    this.pumin1530 = pumin1530;
  }

  public Double getPumin1545() {
    return this.pumin1545;
  }

  public void setPumin1545(Double pumin1545) {
    this.pumin1545 = pumin1545;
  }

  public Double getPumin1600() {
    return this.pumin1600;
  }

  public void setPumin1600(Double pumin1600) {
    this.pumin1600 = pumin1600;
  }

  public Double getPumin1615() {
    return this.pumin1615;
  }

  public void setPumin1615(Double pumin1615) {
    this.pumin1615 = pumin1615;
  }

  public Double getPumin1630() {
    return this.pumin1630;
  }

  public void setPumin1630(Double pumin1630) {
    this.pumin1630 = pumin1630;
  }

  public Double getPumin1645() {
    return this.pumin1645;
  }

  public void setPumin1645(Double pumin1645) {
    this.pumin1645 = pumin1645;
  }

  public Double getPumin1700() {
    return this.pumin1700;
  }

  public void setPumin1700(Double pumin1700) {
    this.pumin1700 = pumin1700;
  }

  public Double getPumin1715() {
    return this.pumin1715;
  }

  public void setPumin1715(Double pumin1715) {
    this.pumin1715 = pumin1715;
  }

  public Double getPumin1730() {
    return this.pumin1730;
  }

  public void setPumin1730(Double pumin1730) {
    this.pumin1730 = pumin1730;
  }

  public Double getPumin1745() {
    return this.pumin1745;
  }

  public void setPumin1745(Double pumin1745) {
    this.pumin1745 = pumin1745;
  }

  public Double getPumin1800() {
    return this.pumin1800;
  }

  public void setPumin1800(Double pumin1800) {
    this.pumin1800 = pumin1800;
  }

  public Double getPumin1815() {
    return this.pumin1815;
  }

  public void setPumin1815(Double pumin1815) {
    this.pumin1815 = pumin1815;
  }

  public Double getPumin1830() {
    return this.pumin1830;
  }

  public void setPumin1830(Double pumin1830) {
    this.pumin1830 = pumin1830;
  }

  public Double getPumin1845() {
    return this.pumin1845;
  }

  public void setPumin1845(Double pumin1845) {
    this.pumin1845 = pumin1845;
  }

  public Double getPumin1900() {
    return this.pumin1900;
  }

  public void setPumin1900(Double pumin1900) {
    this.pumin1900 = pumin1900;
  }

  public Double getPumin1915() {
    return this.pumin1915;
  }

  public void setPumin1915(Double pumin1915) {
    this.pumin1915 = pumin1915;
  }

  public Double getPumin1930() {
    return this.pumin1930;
  }

  public void setPumin1930(Double pumin1930) {
    this.pumin1930 = pumin1930;
  }

  public Double getPumin1945() {
    return this.pumin1945;
  }

  public void setPumin1945(Double pumin1945) {
    this.pumin1945 = pumin1945;
  }

  public Double getPumin2000() {
    return this.pumin2000;
  }

  public void setPumin2000(Double pumin2000) {
    this.pumin2000 = pumin2000;
  }

  public Double getPumin2015() {
    return this.pumin2015;
  }

  public void setPumin2015(Double pumin2015) {
    this.pumin2015 = pumin2015;
  }

  public Double getPumin2030() {
    return this.pumin2030;
  }

  public void setPumin2030(Double pumin2030) {
    this.pumin2030 = pumin2030;
  }

  public Double getPumin2045() {
    return this.pumin2045;
  }

  public void setPumin2045(Double pumin2045) {
    this.pumin2045 = pumin2045;
  }

  public Double getPumin2100() {
    return this.pumin2100;
  }

  public void setPumin2100(Double pumin2100) {
    this.pumin2100 = pumin2100;
  }

  public Double getPumin2115() {
    return this.pumin2115;
  }

  public void setPumin2115(Double pumin2115) {
    this.pumin2115 = pumin2115;
  }

  public Double getPumin2130() {
    return this.pumin2130;
  }

  public void setPumin2130(Double pumin2130) {
    this.pumin2130 = pumin2130;
  }

  public Double getPumin2145() {
    return this.pumin2145;
  }

  public void setPumin2145(Double pumin2145) {
    this.pumin2145 = pumin2145;
  }

  public Double getPumin2200() {
    return this.pumin2200;
  }

  public void setPumin2200(Double pumin2200) {
    this.pumin2200 = pumin2200;
  }

  public Double getPumin2215() {
    return this.pumin2215;
  }

  public void setPumin2215(Double pumin2215) {
    this.pumin2215 = pumin2215;
  }

  public Double getPumin2230() {
    return this.pumin2230;
  }

  public void setPumin2230(Double pumin2230) {
    this.pumin2230 = pumin2230;
  }

  public Double getPumin2245() {
    return this.pumin2245;
  }

  public void setPumin2245(Double pumin2245) {
    this.pumin2245 = pumin2245;
  }

  public Double getPumin2300() {
    return this.pumin2300;
  }

  public void setPumin2300(Double pumin2300) {
    this.pumin2300 = pumin2300;
  }

  public Double getPumin2315() {
    return this.pumin2315;
  }

  public void setPumin2315(Double pumin2315) {
    this.pumin2315 = pumin2315;
  }

  public Double getPumin2330() {
    return this.pumin2330;
  }

  public void setPumin2330(Double pumin2330) {
    this.pumin2330 = pumin2330;
  }

  public Double getPumin2345() {
    return this.pumin2345;
  }

  public void setPumin2345(Double pumin2345) {
    this.pumin2345 = pumin2345;
  }

}
