package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

/**
 * SiteSla generated by hbm2java
 */
public class SiteSla implements java.io.Serializable {

  private int siteId;
  private Site site;
  private Integer maxNumberCall;
  private Integer maxNumberCallDaily;

  public SiteSla() {
  }

  public SiteSla(Site site) {
    this.site = site;
  }

  public SiteSla(Site site, Integer maxNumberCall, Integer maxNumberCallDaily) {
    this.site = site;
    this.maxNumberCall = maxNumberCall;
    this.maxNumberCallDaily = maxNumberCallDaily;
  }

  public int getSiteId() {
    return this.siteId;
  }

  public void setSiteId(int siteId) {
    this.siteId = siteId;
  }

  public Site getSite() {
    return this.site;
  }

  public void setSite(Site site) {
    this.site = site;
  }

  public Integer getMaxNumberCall() {
    return this.maxNumberCall;
  }

  public void setMaxNumberCall(Integer maxNumberCall) {
    this.maxNumberCall = maxNumberCall;
  }

  public Integer getMaxNumberCallDaily() {
    return this.maxNumberCallDaily;
  }

  public void setMaxNumberCallDaily(Integer maxNumberCallDaily) {
    this.maxNumberCallDaily = maxNumberCallDaily;
  }

}
