    package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Site generated by hbm2java
 */
public class Site implements java.io.Serializable {

  @Min(1)
  private int id;
  private City city;
  private Transformer transformer;
  private String name;
  private String street;
  private String streetNumber;
  private Set siteConditionProfiles = new HashSet(0);
  private SiteSla siteSla;
  private Set prosumerHasSites = new HashSet(0);
  private SiteMetric siteMetric;
  private Set siteConditionRaws = new HashSet(0);
  @Size(min = 1)
  private Set equipments = new HashSet(0);

  public Site() {
  }

  public Site(int id, City city, Transformer transformer) {
    this.id = id;
    this.city = city;
    this.transformer = transformer;
  }

  public Site(int id, City city, Transformer transformer, String name, String street, String streetNumber,
      Set siteConditionProfiles, SiteSla siteSla, Set prosumerHasSites, SiteMetric siteMetric, Set siteConditionRaws,
      Set equipments) {
    this.id = id;
    this.city = city;
    this.transformer = transformer;
    this.name = name;
    this.street = street;
    this.streetNumber = streetNumber;
    this.siteConditionProfiles = siteConditionProfiles;
    this.siteSla = siteSla;
    this.prosumerHasSites = prosumerHasSites;
    this.siteMetric = siteMetric;
    this.siteConditionRaws = siteConditionRaws;
    this.equipments = equipments;
  }

  public int getId() {
    return this.id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public City getCity() {
    return this.city;
  }

  public void setCity(City city) {
    this.city = city;
  }

  public Transformer getTransformer() {
    return this.transformer;
  }

  public void setTransformer(Transformer transformer) {
    this.transformer = transformer;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getStreet() {
    return this.street;
  }

  public void setStreet(String street) {
    this.street = street;
  }

  public String getStreetNumber() {
    return this.streetNumber;
  }

  public void setStreetNumber(String streetNumber) {
    this.streetNumber = streetNumber;
  }

  public Set getSiteConditionProfiles() {
    return this.siteConditionProfiles;
  }

  public void setSiteConditionProfiles(Set siteConditionProfiles) {
    this.siteConditionProfiles = siteConditionProfiles;
  }

  public SiteSla getSiteSla() {
    return this.siteSla;
  }

  public void setSiteSla(SiteSla siteSla) {
    this.siteSla = siteSla;
  }

  public Set getProsumerHasSites() {
    return this.prosumerHasSites;
  }

  public void setProsumerHasSites(Set prosumerHasSites) {
    this.prosumerHasSites = prosumerHasSites;
  }

  public SiteMetric getSiteMetric() {
    return this.siteMetric;
  }

  public void setSiteMetric(SiteMetric siteMetric) {
    this.siteMetric = siteMetric;
  }

  public Set getSiteConditionRaws() {
    return this.siteConditionRaws;
  }

  public void setSiteConditionRaws(Set siteConditionRaws) {
    this.siteConditionRaws = siteConditionRaws;
  }

  public Set getEquipments() {
    return this.equipments;
  }

  public void setEquipments(Set equipments) {
    this.equipments = equipments;
  }

}
