package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

import org.joda.time.DateTime;

/**
 * SiteConditionRaw generated by hbm2java
 */
public class SiteConditionRaw implements java.io.Serializable {

  private int id;
  private DateTime timestamp;
  private Site site;
  private String type;
  private Double value;

  public SiteConditionRaw() {
  }

  public SiteConditionRaw(int id, Site site) {
    this.id = id;
    this.site = site;
  }

  public SiteConditionRaw(int id, Site site, String type, Double value) {
    this.id = id;
    this.site = site;
    this.type = type;
    this.value = value;
  }

  public int getId() {
    return this.id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public DateTime getTimestamp() {
    return this.timestamp;
  }

  public void setTimestamp(DateTime timestamp) {
    this.timestamp = timestamp;
  }

  public Site getSite() {
    return this.site;
  }

  public void setSite(Site site) {
    this.site = site;
  }

  public String getType() {
    return this.type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Double getValue() {
    return this.value;
  }

  public void setValue(Double value) {
    this.value = value;
  }

}
