package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

/**
 * SiteMetric generated by hbm2java
 */
public class SiteMetric implements java.io.Serializable {

  private int siteId;
  private Site site;
  private Double siteReliability;
  private Double siteBalance;
  private Integer numberRequest;

  public SiteMetric() {
  }

  public SiteMetric(Site site) {
    this.site = site;
  }

  public SiteMetric(Site site, Double siteReliability, Double siteBalance, Integer numberRequest) {
    this.site = site;
    this.siteReliability = siteReliability;
    this.siteBalance = siteBalance;
    this.numberRequest = numberRequest;
  }

  public int getSiteId() {
    return this.siteId;
  }

  public void setSiteId(int siteId) {
    this.siteId = siteId;
  }

  public Site getSite() {
    return this.site;
  }

  public void setSite(Site site) {
    this.site = site;
  }

  public Double getSiteReliability() {
    return this.siteReliability;
  }

  public void setSiteReliability(Double siteReliability) {
    this.siteReliability = siteReliability;
  }

  public Double getSiteBalance() {
    return this.siteBalance;
  }

  public void setSiteBalance(Double siteBalance) {
    this.siteBalance = siteBalance;
  }

  public Integer getNumberRequest() {
    return this.numberRequest;
  }

  public void setNumberRequest(Integer numberRequest) {
    this.numberRequest = numberRequest;
  }

}
