package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Transformer generated by hbm2java
 */
public class Transformer implements java.io.Serializable {

  private int id;
  private DsoTerritory dsoTerritory;
  private Integer idParent;
  private String location;
  private Set sites = new HashSet(0);

  public Transformer() {
  }

  public Transformer(int id, DsoTerritory dsoTerritory) {
    this.id = id;
    this.dsoTerritory = dsoTerritory;
  }

  public Transformer(int id, DsoTerritory dsoTerritory, Integer idParent, String location, Set sites) {
    this.id = id;
    this.dsoTerritory = dsoTerritory;
    this.idParent = idParent;
    this.location = location;
    this.sites = sites;
  }

  public int getId() {
    return this.id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public DsoTerritory getDsoTerritory() {
    return this.dsoTerritory;
  }

  public void setDsoTerritory(DsoTerritory dsoTerritory) {
    this.dsoTerritory = dsoTerritory;
  }

  public Integer getIdParent() {
    return this.idParent;
  }

  public void setIdParent(Integer idParent) {
    this.idParent = idParent;
  }

  public String getLocation() {
    return this.location;
  }

  public void setLocation(String location) {
    this.location = location;
  }

  public Set getSites() {
    return this.sites;
  }

  public void setSites(Set sites) {
    this.sites = sites;
  }

}
