package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

import org.joda.time.DateTime;

/**
 * WeatherConditionId generated by hbm2java
 */
public class WeatherConditionId implements java.io.Serializable {

  private int cityId;
  private DateTime timestamp;
  private String tyoe;

  public WeatherConditionId() {
  }

  public WeatherConditionId(int cityId, DateTime timestamp, String tyoe) {
    this.cityId = cityId;
    this.timestamp = timestamp;
    this.tyoe = tyoe;
  }

  public int getCityId() {
    return this.cityId;
  }

  public void setCityId(int cityId) {
    this.cityId = cityId;
  }

  public DateTime getTimestamp() {
    return this.timestamp;
  }

  public void setTimestamp(DateTime timestamp) {
    this.timestamp = timestamp;
  }

  public String getTyoe() {
    return this.tyoe;
  }

  public void setTyoe(String tyoe) {
    this.tyoe = tyoe;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof WeatherConditionId))
      return false;
    WeatherConditionId castOther = (WeatherConditionId) other;

    return (this.getCityId() == castOther.getCityId())
        && ((this.getTimestamp() == castOther.getTimestamp()) || (this.getTimestamp() != null && castOther.getTimestamp() != null && this
            .getTimestamp().equals(castOther.getTimestamp())))
        && ((this.getTyoe() == castOther.getTyoe()) || (this.getTyoe() != null && castOther.getTyoe() != null && this.getTyoe()
            .equals(castOther.getTyoe())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + this.getCityId();
    result = 37 * result + (getTimestamp() == null ? 0 : this.getTimestamp().hashCode());
    result = 37 * result + (getTyoe() == null ? 0 : this.getTyoe().hashCode());
    return result;
  }

}
