package com.wattics.vimsen.entities;

// Generated 19-gen-2016 16.17.04 by Hibernate Tools 3.4.0.CR1

/**
 * WeatherCondition generated by hbm2java
 */
public class WeatherCondition implements java.io.Serializable {

  private WeatherConditionId id;
  private City city;
  private Float value;

  public WeatherCondition() {
  }

  public WeatherCondition(WeatherConditionId id, City city) {
    this.id = id;
    this.city = city;
  }

  public WeatherCondition(WeatherConditionId id, City city, Float value) {
    this.id = id;
    this.city = city;
    this.value = value;
  }

  public WeatherConditionId getId() {
    return this.id;
  }

  public void setId(WeatherConditionId id) {
    this.id = id;
  }

  public City getCity() {
    return this.city;
  }

  public void setCity(City city) {
    this.city = city;
  }

  public Float getValue() {
    return this.value;
  }

  public void setValue(Float value) {
    this.value = value;
  }

}
